#!/usr/bin/env bash
# test-org-build.sh - Tests for org build pipeline
set +e

source "$(dirname "$0")/test-framework.sh"

startup_test_setup "Org Build Tests"

# Source org modules
source "$TETRA_SRC/bash/org/org.sh"

# ─── Init ───

test_org_build_init_creates_sections() {
    org_build_init "buildtest" >/dev/null 2>&1
    local dir="$TETRA_DIR/orgs/buildtest/sections"
    [[ -f "$dir/00-org.toml" ]] &&
    [[ -f "$dir/10-infrastructure.toml" ]] &&
    [[ -f "$dir/20-storage.toml" ]] &&
    [[ -f "$dir/25-pdata.toml" ]] &&
    [[ -f "$dir/30-resources.toml" ]] &&
    [[ -f "$dir/40-services.toml" ]] &&
    [[ -f "$dir/50-custom.toml" ]]
}

# ─── Build ───

test_org_build_compiles() {
    org_build "buildtest" >/dev/null 2>&1
    [[ -f "$TETRA_DIR/orgs/buildtest/tetra.toml" ]]
}

test_org_build_header() {
    grep -q "GENERATED by 'org build'" "$TETRA_DIR/orgs/buildtest/tetra.toml"
}

test_org_build_all_sections_present() {
    local toml="$TETRA_DIR/orgs/buildtest/tetra.toml"
    grep -q '# --- 00-org.toml ---' "$toml" &&
    grep -q '# --- 10-infrastructure.toml ---' "$toml" &&
    grep -q '# --- 20-storage.toml ---' "$toml" &&
    grep -q '# --- 50-custom.toml ---' "$toml"
}

# ─── Dirty Detection ───

test_org_build_dirty_detection() {
    # Touch a section file to make it newer than tetra.toml
    sleep 1
    touch "$TETRA_DIR/orgs/buildtest/sections/00-org.toml"
    _org_is_dirty "buildtest"
}

test_org_build_clean_after_build() {
    org_build "buildtest" >/dev/null 2>&1
    ! _org_is_dirty "buildtest"
}

# ─── Validation ───

test_org_build_duplicate_section_fails() {
    local org_name="duptest"
    _create_test_org "$org_name" >/dev/null

    # Add duplicate [org] in another section file
    cat > "$TETRA_DIR/orgs/$org_name/sections/90-dupe.toml" << 'EOF'
[org]
name = "duplicate"
EOF

    # Build should fail
    ! org_build "$org_name" >/dev/null 2>&1
}

# ─── Env Count ───

test_org_build_env_count() {
    local toml="$TETRA_DIR/orgs/buildtest/tetra.toml"
    local count
    count=$(grep -c '^\[env\.' "$toml" 2>/dev/null || echo 0)
    # Default init creates [env.local] in 10-infrastructure.toml
    [[ "$count" -ge 1 ]]
}

# ─── Run ───

log_section "Org Build Init"
run_test "org_build_init creates all section files" test_org_build_init_creates_sections

log_section "Org Build Compile"
run_test "org build produces tetra.toml" test_org_build_compiles
run_test "tetra.toml has GENERATED header" test_org_build_header
run_test "all section filenames appear as markers" test_org_build_all_sections_present

log_section "Dirty Detection"
run_test "touch section -> _org_is_dirty returns true" test_org_build_dirty_detection
run_test "after build -> _org_is_dirty returns false" test_org_build_clean_after_build

log_section "Validation"
run_test "duplicate [org] across files -> build fails" test_org_build_duplicate_section_fails

log_section "Environment Count"
run_test "correct number of [env.*] sections" test_org_build_env_count

startup_test_results "Org Build Results"
exit $TESTS_FAILED
