---
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_FEATURE_TOGGLES_DISABLE_SANITIZE_HTML=true
      - GF_USERS_DISABLE_GRAVATAR=true
      - GF_PATHS_HOME_DASHBOARD_UID=9AJV_mnIk
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    networks:
      - monitoring
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=gridranger
      - DOCKER_INFLUXDB_INIT_ORG=pixeljamarcade
      - DOCKER_INFLUXDB_INIT_BUCKET=influxdb_qa
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=gridranger

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  monitoring:
    driver: bridge
