auth_enabled: false

server:
  http_listen_port: 3100
  # grpc_listen_port: 9096 # Optional: uncomment if needed by specific clients

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki # Directory within the container volume for data
  storage:
    filesystem: # Store data on the filesystem (using the 'loki_data' volume)
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1 # Required for standalone mode
  ring:
    kvstore:
      store: inmemory # Simple store for standalone mode

schema_config:
  configs:
    - from: 2020-10-24 # Use a date in the past
      store: boltdb-shipper # Recommended index store type
      object_store: filesystem
      schema: v12 # Schema version (v11 or v12 common for recent Loki)
      index:
        prefix: index_
        period: 24h

# You can add other sections like limits_config, ingester, etc., later if needed,
# but this minimal config should allow Loki to start.
