global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['10.124.0.3:9113']       # prod_priv
      - targets: ['10.124.0.4:9113']       # dev_priv
      - targets: ['137.184.226.163:9113']  # dev_pub

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'telegraf_prod'
    static_configs:
      - targets: ['10.124.0.3:9125']        # prod_priv
      - targets: ['137.184.226.163:9125']   # dev_pub

  - job_name: 'website-monitoring-http'
    metrics_path: /probe
    params:
      module: [http_2xx_prod]
    static_configs:
      - targets:
          - https://pixeljamarcade.com
          - https://dev.pixeljamarcade.com
          - https://qa.pixeljamarcade.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'dev-arcade-endpoints'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://10.124.0.3:8480/           # Main app
          - http://10.124.0.3:8480/api/health # Health check
          - http://10.124.0.3:8480/api/games  # Important endpoints
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'node'
    static_configs:
      - targets:
          - 'localhost:9100'         # Local machine
          - '10.124.0.3:9100'        # prod_priv
          - '10.124.0.4:9100'        # dev_priv (if exists)
          - '137.184.226.163:9100'   # dev_pub (if exists)
