scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['10.124.0.3:9113']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.124.0.3:9100']

  - job_name: 'arcade-service'
    static_configs:
      - targets: ['10.124.0.3:3001']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'telegraf_prod'
    static_configs:
      - targets: ['10.124.0.3:9125']

  - job_name: 'website-monitoring-http'
    metrics_path: /probe
    params:
      module: [http_2xx_prod]
    static_configs:
      - targets:
          - https://pixeljamarcade.com
          - https://qa.pixeljamarcade.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 

