#!/usr/bin/env bash

# TDOCS Help Tree Builders
# Hierarchical command structure with category-based organization
# Categories: doc, find, scan, mod, chuck, pub, ui

# Build main tdocs category
_tdocs_help_build_category() {
    tree_insert "help.tdocs" category \
        title="Document Manager" \
        help="Manage and categorize LLM-generated markdown documents" \
        detail="TDOC tracks metadata for markdown documents generated by LLMs, providing categorization, search, and RAG integration."
}

# ============================================================================
# DOC - Document Operations (env:0 green)
# ============================================================================
_tdocs_help_build_doc_category() {
    tree_insert "help.tdocs.doc" category \
        title="Document Operations" \
        color_token="tdocs.cmd.doc" \
        help="Create, view, and modify document metadata"

    tree_insert "help.tdocs.doc.add" command \
        title="Add/edit metadata" \
        description="Add or edit document metadata interactively" \
        help="Initialize or update metadata for a markdown document" \
        synopsis="tdocs doc add <file> [OPTIONS]" \
        handler="tdocs_add_doc" \
        examples="tdocs doc add docs/NEW_FEATURE.md
tdocs doc add file.md --type spec --lifecycle S"

    tree_insert "help.tdocs.doc.view" command \
        title="Preview document" \
        description="Preview document with color rendering and metadata" \
        help="View document with color rendering and metadata" \
        synopsis="tdocs doc view <file> [OPTIONS]" \
        handler="tdocs_view_doc" \
        examples="tdocs doc view docs/REPL_FIXES.md
tdocs doc view file.md --meta-only"

    tree_insert "help.tdocs.doc.tag" command \
        title="Tag editor" \
        description="Interactive tag editor for documents" \
        help="Interactive tag editor for documents" \
        synopsis="tdocs doc tag <file>" \
        handler="tdocs_tag_interactive"

    tree_insert "help.tdocs.doc.rank" command \
        title="Show ranking" \
        description="Display lifecycle and priority for a document" \
        help="Show the ranking/priority information for a document" \
        synopsis="tdocs doc rank <file>" \
        handler="tdocs_rank_doc"

    tree_insert "help.tdocs.doc.promote" command \
        title="Promote lifecycle" \
        description="Promote document through lifecycle stages" \
        help="Move document from D→W→S→C lifecycle stages" \
        synopsis="tdocs doc promote <file>" \
        handler="tdocs_promote_doc" \
        examples="tdocs doc promote draft.md"

    # doc flags
    tree_insert "help.tdocs.doc.add.--type" option title="Document type" \
        help="Type of document" completion_values="spec,guide,reference,bug-fix,refactor,plan,summary"
    tree_insert "help.tdocs.doc.add.--lifecycle" option title="Lifecycle stage" \
        help="Lifecycle stage" completion_values="D,W,S,C,X"
    tree_insert "help.tdocs.doc.add.--module" option title="Module name" help="Module association"
    tree_insert "help.tdocs.doc.add.--tags" option title="Tags" help="Comma-separated tags"
    tree_insert "help.tdocs.doc.view.--pager" flag title="Use pager" help="Display output in pager"
    tree_insert "help.tdocs.doc.view.--meta-only" flag title="Metadata only" help="Show only metadata"
    tree_insert "help.tdocs.doc.view.--raw" flag title="Raw output" help="Show raw file with frontmatter"
}

# ============================================================================
# FIND - Query Operations (mode:0 blue)
# ============================================================================
_tdocs_help_build_find_category() {
    tree_insert "help.tdocs.find" category \
        title="Query Operations" \
        color_token="tdocs.cmd.find" \
        help="Search, list, and filter documents"

    tree_insert "help.tdocs.find.ls" command \
        title="List documents" \
        description="List tracked documents with filters and preview" \
        help="List all tracked documents with filters and preview" \
        synopsis="tdocs find ls [OPTIONS]" \
        handler="tdocs_ls_docs" \
        examples="tdocs find ls
tdocs find ls --module rag
tdocs find ls --type spec --lifecycle S"

    tree_insert "help.tdocs.find.search" command \
        title="Search documents" \
        description="Full-text search across all documents" \
        help="Full-text search across all documents" \
        synopsis="tdocs find search <query>" \
        handler="tdocs_search_docs" \
        examples="tdocs find search 'bash completion system'"

    tree_insert "help.tdocs.find.evidence" command \
        title="Evidence ranking" \
        description="Get evidence-weighted document list for RAG" \
        help="Get evidence-weighted document list for RAG" \
        synopsis="tdocs find evidence <query>" \
        handler="tdocs_evidence_for_query"

    tree_insert "help.tdocs.find.filter" command \
        title="Filter documents" \
        description="Apply complex filters to document list" \
        help="Filter documents by multiple criteria" \
        synopsis="tdocs find filter [OPTIONS]" \
        handler="tdocs_filter_docs" \
        examples="tdocs find filter --module rag --type spec
tdocs find filter --lifecycle C --recent 7d"

    # find flags
    tree_insert "help.tdocs.find.ls.--module" option title="Module filter" help="Filter by module name"
    tree_insert "help.tdocs.find.ls.--type" option title="Type filter" help="Filter by document type" \
        completion_values="spec,guide,reference,bug-fix,refactor,plan,summary"
    tree_insert "help.tdocs.find.ls.--lifecycle" option title="Lifecycle filter" help="Filter by lifecycle" \
        completion_values="D,W,S,C,X"
    tree_insert "help.tdocs.find.ls.--preview" flag title="Show preview" help="Display metadata preview"
    tree_insert "help.tdocs.find.ls.--pager" flag title="Use pager" help="Display output in pager"
}

# ============================================================================
# SCAN - Discovery & Audit (verbs:3 orange)
# ============================================================================
_tdocs_help_build_scan_category() {
    tree_insert "help.tdocs.scan" category \
        title="Discovery & Audit" \
        color_token="tdocs.cmd.scan" \
        help="Discover new documents and audit existing ones"

    tree_insert "help.tdocs.scan.discover" command \
        title="Discover documents" \
        description="Scan for undocumented markdown files" \
        help="Scan for undocumented markdown files and optionally initialize them" \
        synopsis="tdocs scan discover [--auto-init]" \
        handler="tdocs_discover_docs"

    tree_insert "help.tdocs.scan.audit" command \
        title="Audit documents" \
        description="Find documents without metadata" \
        help="Find documents without metadata" \
        synopsis="tdocs scan audit" \
        handler="tdocs_audit_docs"

    tree_insert "help.tdocs.scan.doctor" command \
        title="Health check" \
        description="Diagnose and repair database issues" \
        help="Check for stale entries, missing metadata, and database consistency" \
        synopsis="tdocs scan doctor [--fix|--summary]" \
        handler="tdocs_doctor" \
        examples="tdocs scan doctor
tdocs scan doctor --fix"

    tree_insert "help.tdocs.scan.run" command \
        title="Scan directory" \
        description="Scan directory for markdown files" \
        help="Scan a directory and update the index" \
        synopsis="tdocs scan run [path]" \
        handler="tdocs_scan_docs"

    # scan flags
    tree_insert "help.tdocs.scan.discover.--auto-init" flag \
        title="Auto-initialize" help="Automatically initialize found documents"
    tree_insert "help.tdocs.scan.doctor.--fix" flag \
        title="Fix issues" help="Automatically fix discovered issues"
    tree_insert "help.tdocs.scan.doctor.--summary" flag \
        title="Summary only" help="Show summary without details"
}

# ============================================================================
# MOD - Module Documentation (nouns:0 purple)
# ============================================================================
_tdocs_help_build_mod_category() {
    tree_insert "help.tdocs.mod" category \
        title="Module Documentation" \
        color_token="tdocs.cmd.mod" \
        help="View and audit module-level documentation"

    tree_insert "help.tdocs.mod.show" command \
        title="Module documentation" \
        description="Show all documentation for a specific module" \
        help="Display specifications, examples, and completeness level for a module" \
        synopsis="tdocs mod show <module_name>" \
        handler="tdocs_module_docs" \
        examples="tdocs mod show tubes"

    tree_insert "help.tdocs.mod.spec" command \
        title="View specification" \
        description="Display the specification document for a module" \
        help="View the specification document for a specific module" \
        synopsis="tdocs mod spec <module_name>" \
        handler="tdocs_show_spec"

    tree_insert "help.tdocs.mod.audit" command \
        title="Audit specifications" \
        description="Check which modules have specifications" \
        help="Audit all modules to see which have specifications" \
        synopsis="tdocs mod audit [--missing]" \
        handler="tdocs_audit_specs"

    tree_insert "help.tdocs.mod.types" command \
        title="Show types" \
        description="Display available document types" \
        help="Show the taxonomy of document types" \
        synopsis="tdocs mod types" \
        handler="tdocs_show_types"

    # mod flags
    tree_insert "help.tdocs.mod.audit.--missing" flag \
        title="Show missing only" help="Show only modules without specifications"
}

# ============================================================================
# CHUCK - LLM Capture (verbs:0 red)
# ============================================================================
_tdocs_help_build_chuck_category() {
    tree_insert "help.tdocs.chuck" category \
        title="LLM Capture" \
        color_token="tdocs.cmd.chuck" \
        help="Capture and manage LLM responses"

    tree_insert "help.tdocs.chuck.save" command \
        title="Save LLM response" \
        help="Save LLM response from stdin or file" \
        synopsis="tdocs chuck save <kind> [--from FILE]" \
        handler="tdocs_chuck_save"

    tree_insert "help.tdocs.chuck.list" command \
        title="List chuck documents" \
        help="List chucked documents with optional filters" \
        synopsis="tdocs chuck list [--kind KIND] [--recent N]" \
        handler="tdocs_chuck_list"

    tree_insert "help.tdocs.chuck.view" command \
        title="View chuck document" \
        help="Display a chucked document" \
        synopsis="tdocs chuck view <id>" \
        handler="tdocs_chuck_view"

    tree_insert "help.tdocs.chuck.promote" command \
        title="Promote to reference" \
        help="Promote chuck document to reference directory" \
        synopsis="tdocs chuck promote <id> <dest_path>" \
        handler="tdocs_chuck_promote"

    tree_insert "help.tdocs.chuck.delete" command \
        title="Delete chuck document" \
        help="Remove a chuck document" \
        synopsis="tdocs chuck delete <id> [--force]" \
        handler="tdocs_chuck_delete"

    tree_insert "help.tdocs.chuck.search" command \
        title="Search chuck documents" \
        help="Full-text search across chuck documents" \
        synopsis="tdocs chuck search <query>" \
        handler="tdocs_chuck_search"

    # chuck flags
    tree_insert "help.tdocs.chuck.list.--kind" option \
        title="Filter by kind" help="Filter by document kind"
    tree_insert "help.tdocs.chuck.list.--recent" option \
        title="Recent count" help="Show N most recent"
    tree_insert "help.tdocs.chuck.delete.--force" flag \
        title="Force delete" help="Delete without confirmation"
}

# ============================================================================
# PUB - Publishing (mode:6 cyan)
# ============================================================================
_tdocs_help_build_pub_category() {
    tree_insert "help.tdocs.pub" category \
        title="Publishing" \
        color_token="tdocs.cmd.pub" \
        help="Publish documentation to external targets"

    tree_insert "help.tdocs.pub.publish" command \
        title="Publish documentation" \
        description="Publish documentation to configured endpoint" \
        help="Publish docs to Hugging Face Spaces or other targets" \
        synopsis="tdocs pub publish <source> <target>" \
        handler="tdocs_publish"

    tree_insert "help.tdocs.pub.targets" command \
        title="List targets" \
        description="List available publish targets" \
        help="Show configured publishing targets" \
        synopsis="tdocs pub targets" \
        handler="tdocs_list_publish_targets"

    tree_insert "help.tdocs.pub.nginx" command \
        title="Generate nginx config" \
        description="Generate nginx proxy configuration" \
        help="Generate nginx configuration for reverse proxy" \
        synopsis="tdocs pub nginx <target>" \
        handler="tdocs_generate_nginx_config"
}

# ============================================================================
# UI - Interface & Info (env:2 green)
# ============================================================================
_tdocs_help_build_ui_category() {
    tree_insert "help.tdocs.ui" category \
        title="Interface & Info" \
        color_token="tdocs.cmd.ui" \
        help="Interactive tools and information"

    tree_insert "help.tdocs.ui.browse" command \
        title="Interactive browser" \
        description="Launch interactive REPL for browsing documents" \
        help="Launch interactive REPL for browsing documents" \
        synopsis="tdocs ui browse" \
        handler="tdocs_repl" \
        examples="tdocs ui browse"

    tree_insert "help.tdocs.ui.review" command \
        title="Interactive review" \
        description="Interactively manage documents (archive, formalize, move, delete)" \
        help="Scan for documents and prompt for actions" \
        synopsis="tdocs ui review [wip|all]" \
        handler="tdocs_review_interactive" \
        examples="tdocs ui review
tdocs ui review wip"

    tree_insert "help.tdocs.ui.colors" command \
        title="Color explorer" \
        description="Interactive color explorer for TDS tokens" \
        help="Explore and test TDS color tokens interactively" \
        synopsis="tdocs ui colors" \
        handler="tdocs_color_explorer"

    tree_insert "help.tdocs.ui.about" command \
        title="About tdocs" \
        description="Show comprehensive tdocs documentation and usage guide" \
        help="Display the full tdocs documentation" \
        synopsis="tdocs ui about [OPTIONS]" \
        handler="tdocs_about" \
        examples="tdocs ui about
tdocs ui about --no-pager"

    # ui flags
    tree_insert "help.tdocs.ui.review.mode" option \
        title="Review mode" help="Mode: wip (WIP docs only, default) or all" \
        completion_values="wip,all"
    tree_insert "help.tdocs.ui.about.--no-pager" flag \
        title="Disable pager" help="Display without pager"
}

# ============================================================================
# Context commands (special - not categorized)
# ============================================================================
_tdocs_help_build_context_commands() {
    tree_insert "help.tdocs.ctx" command \
        title="Context management" \
        description="Manage PData project context T[org:project:subject]" \
        help="Set, clear, or show project context" \
        synopsis="tdocs ctx [set|clear|show]" \
        handler="tdocs_ctx"

    tree_insert "help.tdocs.help" command \
        title="Help" \
        description="Show help for a topic" \
        help="Display help information" \
        synopsis="tdocs help [topic]" \
        handler="tdocs_help"
}

# Main builder - calls all sub-builders
_tdocs_build_help_tree() {
    _tdocs_help_build_category
    _tdocs_help_build_doc_category
    _tdocs_help_build_find_category
    _tdocs_help_build_scan_category
    _tdocs_help_build_mod_category
    _tdocs_help_build_chuck_category
    _tdocs_help_build_pub_category
    _tdocs_help_build_ui_category
    _tdocs_help_build_context_commands
}
