#!/usr/bin/env bash

# TDOCS Help Tree Builders
# Extracted from tdocs.sh for maintainability
# Each builder defines tree_insert calls for a specific category

# Build main tdocs category
_tdocs_help_build_category() {
    tree_insert "help.tdocs" category \
        title="Document Manager" \
        help="Manage and categorize LLM-generated markdown documents" \
        detail="TDOC tracks metadata for markdown documents generated by LLMs, providing categorization, search, and RAG integration."
}

# Build core commands
_tdocs_help_build_core_commands() {
    tree_insert "help.tdocs.init" command \
        title="Initialize document" \
        description="Initialize document with metadata (interactive or non-interactive)" \
        help="Add metadata to document (interactive or non-interactive)" \
        synopsis="tdocs init <file> [OPTIONS]" \
        handler="tdocs_init_doc" \
        examples="tdocs init bash/rag/docs/NEW_FEATURE.md
tdocs init docs/API_SPEC.md --core --type spec"

    tree_insert "help.tdocs.view" command \
        title="Preview document" \
        description="Preview document with color rendering and metadata" \
        help="View document with color rendering and metadata" \
        synopsis="tdocs view <file> [OPTIONS]" \
        handler="tdocs_view_doc" \
        examples="tdocs view bash/rag/docs/REPL_FIXES.md
tdocs view file.md --meta-only"

    tree_insert "help.tdocs.tag" command \
        title="Tag editor" \
        description="Interactive tag editor for documents" \
        help="Interactive tag editor for documents" \
        synopsis="tdocs tag <file>" \
        handler="tdocs_tag_interactive"

    tree_insert "help.tdocs.ls" command \
        title="List documents" \
        description="List tracked documents with filters and preview" \
        help="List all tracked documents with filters and preview" \
        synopsis="tdocs ls [OPTIONS]" \
        handler="tdocs_ls_docs" \
        details="Shows detailed list with color-coded category badges, metadata headers, and full paths." \
        examples="tdocs ls
tdocs ls --core
tdocs ls --module rag
tdocs ls --core --module rag --preview"

    tree_insert "help.tdocs.search" command \
        title="Search documents" \
        description="Full-text search across all documents" \
        help="Full-text search across all documents" \
        synopsis="tdocs search <query>" \
        handler="tdocs_search_docs" \
        examples="tdocs search 'bash completion system'"

    tree_insert "help.tdocs.evidence" command \
        title="Evidence ranking" \
        description="Get evidence-weighted document list for RAG" \
        help="Get evidence-weighted document list for RAG" \
        synopsis="tdocs evidence <query>" \
        handler="tdocs_evidence_for_query"

    tree_insert "help.tdocs.audit" command \
        title="Audit documents" \
        description="Find documents without metadata" \
        help="Find documents without metadata" \
        synopsis="tdocs audit" \
        handler="tdocs_audit_docs"

    tree_insert "help.tdocs.browse" command \
        title="Interactive browser" \
        description="Launch interactive REPL for browsing documents" \
        help="Launch interactive REPL for browsing documents" \
        synopsis="tdocs browse" \
        details="Hybrid mode REPL: shell commands work directly, /cmd for tdocs commands." \
        examples="tdocs browse"

    tree_insert "help.tdocs.about" command \
        title="About tdocs" \
        description="Show comprehensive tdocs documentation and usage guide" \
        help="Display the full tdocs documentation" \
        synopsis="tdocs about [OPTIONS]" \
        handler="tdocs_about" \
        examples="tdocs about
tdocs about --no-pager"

    tree_insert "help.tdocs.discover" command \
        title="Discover documents" \
        description="Scan for undocumented markdown files" \
        help="Scan for undocumented markdown files and optionally initialize them" \
        synopsis="tdocs discover [--auto-init]" \
        handler="tdocs_discover_docs"

    tree_insert "help.tdocs.doctor" command \
        title="Health check" \
        description="Diagnose and repair database issues" \
        help="Check for stale entries, missing metadata, and database consistency" \
        synopsis="tdocs doctor [--fix|--summary]" \
        handler="tdocs_doctor" \
        examples="tdocs doctor
tdocs doctor --fix"
}

# Build review commands
_tdocs_help_build_review_commands() {
    tree_insert "help.tdocs.review" command \
        title="Interactive review" \
        description="Interactively manage documents (archive, formalize, move, delete)" \
        help="Scan for documents and prompt for actions" \
        synopsis="tdocs review [wip|all]" \
        handler="tdocs_review_interactive" \
        details="Walks through documents and prompts for: [v]iew, [a]rchive, [f]ormalize, [m]ove, [k]eep, [d]elete, [s]kip, or [q]uit." \
        examples="tdocs review
tdocs review wip"

    tree_insert "help.tdocs.review.mode" option \
        title="Review mode" \
        help="Mode: wip (WIP docs only, default) or all" \
        completion_values="wip,all"
}

# Build chuck commands
_tdocs_help_build_chuck_commands() {
    tree_insert "help.tdocs.chuck" command \
        title="Chuck LLM responses" \
        description="Capture LLM responses as lower-grade technical documentation" \
        help="Capture LLM responses as lower-grade technical documentation" \
        synopsis="tdocs chuck <subcommand>" \
        handler="tdocs_action_chuck" \
        details="Chuck stores LLM responses in \$TETRA_DIR/tdocs/chuck/ with epoch timestamps." \
        examples="tdocs chuck save tree < llm_response.md
tdocs chuck list --recent 10"

    tree_insert "help.tdocs.chuck.save" command \
        title="Save LLM response" \
        help="Save LLM response from stdin or file" \
        synopsis="tdocs chuck save <kind> [--from FILE]"

    tree_insert "help.tdocs.chuck.list" command \
        title="List chuck documents" \
        help="List chucked documents with optional filters" \
        synopsis="tdocs chuck list [--kind KIND] [--recent N]"

    tree_insert "help.tdocs.chuck.view" command \
        title="View chuck document" \
        help="Display a chucked document" \
        synopsis="tdocs chuck view <id>"

    tree_insert "help.tdocs.chuck.promote" command \
        title="Promote to reference" \
        help="Promote chuck document to reference directory" \
        synopsis="tdocs chuck promote <id> <dest_path>"

    tree_insert "help.tdocs.chuck.delete" command \
        title="Delete chuck document" \
        help="Remove a chuck document" \
        synopsis="tdocs chuck delete <id> [--force]"

    tree_insert "help.tdocs.chuck.search" command \
        title="Search chuck documents" \
        help="Full-text search across chuck documents" \
        synopsis="tdocs chuck search <query>"
}

# Build module documentation commands
_tdocs_help_build_module_commands() {
    tree_insert "help.tdocs.module" command \
        title="Module documentation" \
        description="Show all documentation for a specific module" \
        help="Display specifications, examples, and completeness level for a module" \
        synopsis="tdocs module <module_name>" \
        handler="tdoc_module_docs" \
        examples="tdocs module tubes"

    tree_insert "help.tdocs.spec" command \
        title="View module specification" \
        description="Display the specification document for a module" \
        help="View the specification document for a specific module" \
        synopsis="tdocs spec <module_name>" \
        handler="tdoc_show_spec"

    tree_insert "help.tdocs.audit-specs" command \
        title="Audit module specifications" \
        description="Check which modules have specifications" \
        help="Audit all modules to see which have specifications" \
        synopsis="tdocs audit-specs [--missing]" \
        handler="tdoc_audit_specs"

    tree_insert "help.tdocs.audit-specs.--missing" flag \
        title="Show missing only" \
        help="Show only modules without specifications"
}

# Build publish commands
_tdocs_help_build_publish_commands() {
    tree_insert "help.tdocs.publish" command \
        title="Publish documentation" \
        description="Publish documentation to configured endpoint" \
        help="Publish docs to Hugging Face Spaces or other targets" \
        synopsis="tdocs publish <source> <target>" \
        handler="tdocs_publish"

    tree_insert "help.tdocs.nginx-config" command \
        title="Generate nginx config" \
        description="Generate nginx proxy configuration" \
        help="Generate nginx configuration for reverse proxy" \
        synopsis="tdocs nginx-config <target>" \
        handler="tdocs_generate_nginx_config"

    tree_insert "help.tdocs.publish-targets" command \
        title="List publish targets" \
        description="List available publish targets" \
        help="Show configured publishing targets" \
        synopsis="tdocs publish-targets" \
        handler="tdocs_list_publish_targets"

    tree_insert "help.tdocs.colors" command \
        title="Color explorer" \
        description="Interactive color explorer for TDS tokens" \
        help="Explore and test TDS color tokens interactively" \
        synopsis="tdocs colors" \
        handler="tdocs_color_explorer"
}

# Build common flags and options
_tdocs_help_build_flags() {
    # ls flags
    tree_insert "help.tdocs.ls.--core" flag title="Core only" help="List only core documents"
    tree_insert "help.tdocs.ls.--other" flag title="Other only" help="List only other/working documents"
    tree_insert "help.tdocs.ls.--preview" flag title="Show preview" help="Display metadata preview"
    tree_insert "help.tdocs.ls.--module" option title="Module filter" help="Filter by module name"
    tree_insert "help.tdocs.ls.--tags" option title="Tag filter" help="Filter by comma-separated tags"
    tree_insert "help.tdocs.ls.--type" option title="Type filter" help="Filter by document type"
    tree_insert "help.tdocs.ls.--pager" flag title="Use pager" help="Display output in pager"
    tree_insert "help.tdocs.ls.--meta-only" flag title="Metadata only" help="Show only metadata"
    tree_insert "help.tdocs.ls.--raw" flag title="Raw output" help="Show raw file with frontmatter"

    # init flags
    tree_insert "help.tdocs.init.--core" flag title="Core document" help="Mark as core document"
    tree_insert "help.tdocs.init.--other" flag title="Other document" help="Mark as other/working document"
    tree_insert "help.tdocs.init.--type" option title="Document type" help="Type of document" \
        completion_values="spec,guide,bug-fix,refactor,plan,summary"
    tree_insert "help.tdocs.init.--tags" option title="Tags" help="Comma-separated tags"
    tree_insert "help.tdocs.init.--module" option title="Module name" help="Module association"

    # view flags
    tree_insert "help.tdocs.view.--pager" flag title="Use pager" help="Display output in pager"
    tree_insert "help.tdocs.view.--meta-only" flag title="Metadata only" help="Show only metadata"
    tree_insert "help.tdocs.view.--raw" flag title="Raw output" help="Show raw file with frontmatter"

    # about flags
    tree_insert "help.tdocs.about.--no-pager" flag title="Disable pager" help="Display without pager"
    tree_insert "help.tdocs.about.--width" option title="Max content width" help="Maximum content width"
    tree_insert "help.tdocs.about.--margin" option title="Set margins" help="Set both left and right margins"
    tree_insert "help.tdocs.about.--left-margin" option title="Left margin" help="Set left margin in spaces"
    tree_insert "help.tdocs.about.--right-margin" option title="Right margin" help="Set right margin in spaces"

    # list flags (alias of ls)
    tree_insert "help.tdocs.list.--core" flag title="Core only" help="List only core documents"
    tree_insert "help.tdocs.list.--other" flag title="Other only" help="List only other/working documents"
    tree_insert "help.tdocs.list.--preview" flag title="Show preview" help="Display metadata preview"
    tree_insert "help.tdocs.list.--module" option title="Module filter" help="Filter by module name"
    tree_insert "help.tdocs.list.--tags" option title="Tag filter" help="Filter by comma-separated tags"
}

# Main builder - calls all sub-builders
_tdocs_build_help_tree() {
    _tdocs_help_build_category
    _tdocs_help_build_core_commands
    _tdocs_help_build_review_commands
    _tdocs_help_build_chuck_commands
    _tdocs_help_build_module_commands
    _tdocs_help_build_publish_commands
    _tdocs_help_build_flags
}
