#!/usr/bin/env bash

# TMOD Logging Wrapper - TCS 4.0 Compliant
# Auto-generated by generate_module_log.sh
# Provides convenience functions for TMOD module logging

# Ensure unified logging is loaded
if ! type tetra_log_event >/dev/null 2>&1; then
    source "${TETRA_SRC}/bash/utils/unified_log.sh"
fi

# === TMOD LOGGING WRAPPERS ===

# Generic TMOD log event
tmod_log() {
    tetra_log_event tmod "$@"
}

# TMOD try events
tmod_log_try() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_try tmod "$verb" "$subject" "$metadata"
}

# TMOD success events
tmod_log_success() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_success tmod "$verb" "$subject" "$metadata"
}

# TMOD fail events
tmod_log_fail() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_fail tmod "$verb" "$subject" "$metadata"
}

# TMOD info events
tmod_log_info() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_info tmod "$verb" "$subject" "$metadata"
}

# TMOD debug events
tmod_log_debug() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_debug tmod "$verb" "$subject" "$metadata"
}

# TMOD warning events
tmod_log_warn() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_warn tmod "$verb" "$subject" "$metadata"
}

# TMOD error events
tmod_log_error() {
    local verb="$1"
    local subject="$2"
    local metadata="${3:-{}}"
    tetra_log_error tmod "$verb" "$subject" "$metadata"
}

# === MODULE-SPECIFIC LOGGING FUNCTIONS ===
# Add your custom logging functions below this line
#
# Example:
# tmod_log_operation_try() {
#     local operation_id="$1"
#     local params="$2"
#     local metadata=$(jq -n --arg params "$params" '{params: $params}')
#     tmod_log_try "operation" "$operation_id" "$metadata"
# }

# === QUERY HELPERS ===

# Query TMOD logs
tmod_log_query() {
    tetra_log_query_module tmod
}

# Query TMOD errors
tmod_log_query_errors() {
    tetra_log_query_module tmod | jq -c 'select(.status == "fail" or .level == "ERROR")'
}

# Query specific verb
tmod_log_query_verb() {
    local verb="$1"
    tetra_log_query_module tmod | jq -c --arg verb "$verb" 'select(.verb == $verb)'
}
