#!/usr/bin/env bash

# TDOCS - Tetra Document Manager
# TCS 3.0-compliant module for managing LLM-generated markdown documents

# Strong globals - ensure TETRA_DIR is set
if [[ -z "$TETRA_DIR" ]]; then
    TETRA_DIR="${HOME}/.tetra"
fi

: "${TDOCS_SRC:=$TETRA_SRC/bash/tdocs}"
: "${TDOCS_DIR:=$TETRA_DIR/tdocs}"

# Source publish module if not already loaded
if [[ -z "$(type -t tdocs_list_publish_targets)" ]]; then
    if [[ -f "$TDOCS_SRC/core/publish.sh" ]]; then
        source "$TDOCS_SRC/core/publish.sh"
    fi
fi

# Module directories
TDOCS_DB_DIR="${TDOCS_DIR}/db"
TDOCS_CONFIG_DIR="${TDOCS_DIR}/config"
TDOCS_CACHE_DIR="${TDOCS_DIR}/cache"

# Export for subshells
export TDOCS_SRC TDOCS_DIR TDOCS_DB_DIR TDOCS_CONFIG_DIR TDOCS_CACHE_DIR

# Load dependencies
TDS_SRC="${TDS_SRC:-$TETRA_SRC/bash/tds}"
if [[ -f "$TDS_SRC/tds.sh" ]]; then
    source "$TDS_SRC/tds.sh"
else
    echo "Warning: TDS not found at $TDS_SRC - color features disabled" >&2
fi

# Load tree-based help system
if [[ -f "$TETRA_SRC/bash/tree/help.sh" ]]; then
    source "$TETRA_SRC/bash/tree/help.sh"
fi

# Load tdocs constants first (taxonomy definitions)
source "$TDOCS_SRC/core/tdocs_constants.sh"

# Load tdocs components
source "$TDOCS_SRC/core/metadata.sh"
source "$TDOCS_SRC/core/database.sh"
source "$TDOCS_SRC/core/index.sh"
source "$TDOCS_SRC/core/classify.sh"
source "$TDOCS_SRC/core/search.sh"
source "$TDOCS_SRC/core/doctor.sh"
source "$TDOCS_SRC/core/chuck.sh"
source "$TDOCS_SRC/core/module_ops.sh"
source "$TDOCS_SRC/core/ranking.sh"
source "$TDOCS_SRC/core/scan.sh"
source "$TDOCS_SRC/core/review.sh"
source "$TDOCS_SRC/core/help.sh"
source "$TDOCS_SRC/ui/tdocs_tokens.sh"
source "$TDOCS_SRC/ui/tags.sh"
source "$TDOCS_SRC/ui/preview.sh"
source "$TDOCS_SRC/ui/interactive.sh"
source "$TDOCS_SRC/integrations/rag_evidence.sh"

# Load actions
source "$TDOCS_SRC/actions/chuck.sh"
source "$TDOCS_SRC/action_interface.sh"

# Build help tree for tdocs
_tdocs_build_help_tree() {
    # Main category
    tree_insert "help.tdocs" category \
        title="Document Manager" \
        help="Manage and categorize LLM-generated markdown documents" \
        detail="TDOC tracks metadata for markdown documents generated by LLMs, providing categorization, search, and RAG integration."

    # Commands
    tree_insert "help.tdocs.init" command \
        title="Initialize document" \
        description="Initialize document with metadata (interactive or non-interactive)" \
        help="Add metadata to document (interactive or non-interactive)" \
        synopsis="tdocs init <file> [OPTIONS]" \
        handler="tdocs_init_doc" \
        examples="tdocs init bash/rag/docs/NEW_FEATURE.md
tdocs init docs/API_SPEC.md --core --type spec"

    tree_insert "help.tdocs.view" command \
        title="Preview document" \
        description="Preview document with color rendering and metadata" \
        help="View document with color rendering and metadata" \
        synopsis="tdocs view <file> [OPTIONS]" \
        handler="tdocs_view_doc" \
        examples="tdocs view bash/rag/docs/REPL_FIXES.md
tdocs view file.md --meta-only"

    tree_insert "help.tdocs.tag" command \
        title="Tag editor" \
        description="Interactive tag editor for documents" \
        help="Interactive tag editor for documents" \
        synopsis="tdocs tag <file>" \
        handler="tdocs_tag_interactive"

    tree_insert "help.tdocs.ls" command \
        title="List documents" \
        description="List tracked documents with filters and preview" \
        help="List all tracked documents with filters and preview" \
        synopsis="tdocs ls [OPTIONS]" \
        handler="tdocs_ls_docs" \
        details="Shows detailed list with color-coded category badges, metadata headers, and full paths." \
        examples="tdocs ls
tdocs ls --core
tdocs ls --module rag
tdocs ls --core --module rag --preview"

    # ls flags (same as list, since ls is an alias)
    tree_insert "help.tdocs.ls.--core" flag \
        title="Core only" \
        help="List only core documents"

    tree_insert "help.tdocs.ls.--other" flag \
        title="Other only" \
        help="List only other/working documents"

    tree_insert "help.tdocs.ls.--preview" flag \
        title="Show preview" \
        help="Display metadata preview for each document"

    tree_insert "help.tdocs.ls.--module" option \
        title="Module filter" \
        help="Filter by module name"

    tree_insert "help.tdocs.ls.--tags" option \
        title="Tag filter" \
        help="Filter by comma-separated tags"

    tree_insert "help.tdocs.ls.--type" option \
        title="Type filter" \
        help="Filter by document type"

    tree_insert "help.tdocs.ls.--pager" flag \
        title="Use pager" \
        help="Display output in pager (less)"

    tree_insert "help.tdocs.ls.--meta-only" flag \
        title="Metadata only" \
        help="Show only metadata, not content"

    tree_insert "help.tdocs.ls.--raw" flag \
        title="Raw output" \
        help="Show raw file with frontmatter"

    tree_insert "help.tdocs.search" command \
        title="Search documents" \
        description="Full-text search across all documents" \
        help="Full-text search across all documents" \
        synopsis="tdocs search <query>" \
        handler="tdocs_search_docs" \
        examples="tdocs search 'bash completion system'"

    tree_insert "help.tdocs.evidence" command \
        title="Evidence ranking" \
        description="Get evidence-weighted document list for RAG" \
        help="Get evidence-weighted document list for RAG" \
        synopsis="tdocs evidence <query>" \
        handler="tdocs_evidence_for_query"

    tree_insert "help.tdocs.audit" command \
        title="Audit documents" \
        description="Find documents without metadata" \
        help="Find documents without metadata" \
        synopsis="tdocs audit" \
        handler="tdocs_audit_docs"

    tree_insert "help.tdocs.browse" command \
        title="Interactive browser" \
        description="Launch interactive REPL for browsing documents" \
        help="Launch interactive REPL for browsing documents" \
        synopsis="tdocs browse" \
        details="Hybrid mode REPL: shell commands work directly, /cmd for tdocs commands. Use /help inside REPL for more info." \
        examples="tdocs browse
# Inside REPL:
# /ls                List all docs
# /filter core       Set filter
# /view README.md    View document
# git status         Shell works too!"

    tree_insert "help.tdocs.index" command \
        title="Index management" \
        description="Show or rebuild document indexes" \
        help="Show or rebuild document indexes" \
        synopsis="tdocs index [--rebuild]"

    tree_insert "help.tdocs.about" command \
        title="About tdocs" \
        description="Show comprehensive tdocs documentation and usage guide" \
        help="Display the full tdocs documentation including features, usage examples, and best practices. Uses TDS markdown renderer with color syntax highlighting and configurable margins for improved readability." \
        synopsis="tdocs about [OPTIONS]" \
        handler="tdocs_about" \
        examples="tdocs about
tdocs about --no-pager
tdocs about --width 100 --margin 8
tdocs about --left-margin 10"

    tree_insert "help.tdocs.about.--no-pager" flag \
        title="Disable pager" \
        help="Display without pager (print to stdout)"

    tree_insert "help.tdocs.about.--width" option \
        title="Max content width" \
        help="Maximum content width (default: terminal width - margins)"

    tree_insert "help.tdocs.about.--margin" option \
        title="Set margins" \
        help="Set both left and right margins (default: 4 spaces)"

    tree_insert "help.tdocs.about.--left-margin" option \
        title="Left margin" \
        help="Set left margin in spaces (default: 4)"

    tree_insert "help.tdocs.about.--right-margin" option \
        title="Right margin" \
        help="Set right margin in spaces (default: 4)"

    # init flags/options
    tree_insert "help.tdocs.init.--core" flag \
        title="Core document" \
        help="Mark as core document (vs working/temporary)"

    tree_insert "help.tdocs.init.--other" flag \
        title="Other document" \
        help="Mark as other/working document"

    tree_insert "help.tdocs.init.--type" option \
        title="Document type" \
        help="Type of document" \
        completion_values="spec,guide,bug-fix,refactor,plan,summary"

    tree_insert "help.tdocs.init.--tags" option \
        title="Tags" \
        help="Comma-separated tags for categorization"

    tree_insert "help.tdocs.init.--module" option \
        title="Module name" \
        help="Module association (auto-detected if in bash/<module>/)"

    # view flags
    tree_insert "help.tdocs.view.--pager" flag \
        title="Use pager" \
        help="Display output in pager (less)"

    tree_insert "help.tdocs.view.--meta-only" flag \
        title="Metadata only" \
        help="Show only metadata, not content"

    tree_insert "help.tdocs.view.--raw" flag \
        title="Raw output" \
        help="Show raw file with frontmatter"

    # list flags
    tree_insert "help.tdocs.list.--core" flag \
        title="Core only" \
        help="List only core documents"

    tree_insert "help.tdocs.list.--other" flag \
        title="Other only" \
        help="List only other/working documents"

    tree_insert "help.tdocs.list.--preview" flag \
        title="Show preview" \
        help="Display metadata preview for each document"

    tree_insert "help.tdocs.list.--module" option \
        title="Module filter" \
        help="Filter by module name"

    tree_insert "help.tdocs.list.--tags" option \
        title="Tag filter" \
        help="Filter by comma-separated tags"

    # Discover command
    tree_insert "help.tdocs.discover" command \
        title="Discover documents" \
        description="Scan for undocumented markdown files and optionally initialize them" \
        help="Scan for undocumented markdown files and optionally initialize them" \
        synopsis="tdocs discover [--auto-init]" \
        handler="tdocs_discover_docs"

    tree_insert "help.tdocs.doctor" command \
        title="Health check" \
        description="Diagnose and repair database issues" \
        help="Check for stale entries, missing metadata, and database consistency" \
        synopsis="tdocs doctor [--fix|--summary]" \
        handler="tdocs_doctor" \
        details="Reports stale database entries and documents without metadata. Use --fix to automatically repair issues." \
        examples="tdocs doctor
tdocs doctor --fix
tdocs doctor --summary"

    # Review commands
    tree_insert "help.tdocs.review" command \
        title="Interactive review" \
        description="Interactively manage documents (archive, formalize, move, delete)" \
        help="Scan for documents and prompt for actions" \
        synopsis="tdocs review [wip|all]" \
        handler="tdocs_review_interactive" \
        details="Walks through documents and prompts for: [v]iew in pager, [a]rchive, [f]ormalize (add metadata), [m]ove, [k]eep, [d]elete, [s]kip, or [q]uit." \
        examples="tdocs review
tdocs review wip
tdocs review all"

    tree_insert "help.tdocs.review.mode" option \
        title="Review mode" \
        help="Mode: wip (WIP docs only, default) or all (all markdown files)" \
        completion_values="wip,all"

    # Chuck command
    tree_insert "help.tdocs.chuck" command \
        title="Chuck LLM responses" \
        description="Capture LLM responses as lower-grade technical documentation" \
        help="Capture LLM responses as lower-grade technical documentation" \
        synopsis="tdocs chuck <subcommand>" \
        handler="tdocs_action_chuck" \
        details="Chuck stores LLM responses in $TETRA_DIR/tdocs/chuck/ with epoch timestamps.
These are lower-grade docs that can later be promoted to reference documentation." \
        examples="tdocs chuck save tree < llm_response.md
tdocs chuck list --recent 10
tdocs chuck promote 1729950000 docs/reference/tree.md"

    # Chuck subcommands
    tree_insert "help.tdocs.chuck.save" command \
        title="Save LLM response" \
        help="Save LLM response from stdin or file" \
        synopsis="tdocs chuck save <kind> [--from FILE]" \
        examples="echo '...' | tdocs chuck save tree
tdocs chuck save boot --from /tmp/response.md"

    tree_insert "help.tdocs.chuck.list" command \
        title="List chuck documents" \
        help="List chucked documents with optional filters" \
        synopsis="tdocs chuck list [--kind KIND] [--recent N]" \
        examples="tdocs chuck list
tdocs chuck list --kind tree --recent 5"

    tree_insert "help.tdocs.chuck.view" command \
        title="View chuck document" \
        help="Display a chucked document" \
        synopsis="tdocs chuck view <id> | --kind <kind>" \
        examples="tdocs chuck view 1729950000
tdocs chuck view --kind tree"

    tree_insert "help.tdocs.chuck.promote" command \
        title="Promote to reference" \
        help="Promote chuck document to reference directory" \
        synopsis="tdocs chuck promote <id> <dest_path>" \
        examples="tdocs chuck promote 1729950000 docs/reference/tree-design.md"

    tree_insert "help.tdocs.chuck.delete" command \
        title="Delete chuck document" \
        help="Remove a chuck document" \
        synopsis="tdocs chuck delete <id> [--force]" \
        examples="tdocs chuck delete 1729950000"

    tree_insert "help.tdocs.chuck.search" command \
        title="Search chuck documents" \
        help="Full-text search across chuck documents" \
        synopsis="tdocs chuck search <query>" \
        examples="tdocs chuck search 'boot optimization'"

    # Module commands
    tree_insert "help.tdocs.module" command \
        title="Module documentation" \
        description="Show all documentation for a specific module" \
        help="Display specifications, examples, and completeness level for a module" \
        synopsis="tdocs module <module_name>" \
        handler="tdoc_module_docs" \
        examples="tdocs module tubes
tdocs module rag"

    tree_insert "help.tdocs.spec" command \
        title="View module specification" \
        description="Display the specification document for a module" \
        help="View the specification document for a specific module" \
        synopsis="tdocs spec <module_name>" \
        handler="tdoc_show_spec" \
        examples="tdocs spec tubes
tdocs spec tdocs"

    tree_insert "help.tdocs.audit-specs" command \
        title="Audit module specifications" \
        description="Check which modules have specifications and their completeness levels" \
        help="Audit all modules to see which have specifications and what completeness level they've achieved" \
        synopsis="tdocs audit-specs [--missing]" \
        handler="tdoc_audit_specs" \
        examples="tdocs audit-specs
tdocs audit-specs --missing"

    tree_insert "help.tdocs.audit-specs.--missing" flag \
        title="Show missing only" \
        help="Show only modules without specifications"

    # Publish commands
    tree_insert "help.tdocs.publish" command \
        title="Publish documentation" \
        description="Publish documentation to configured endpoint" \
        help="Publish docs to Hugging Face Spaces or other targets" \
        synopsis="tdocs publish <source> <target>" \
        handler="tdocs_publish"

    tree_insert "help.tdocs.nginx-config" command \
        title="Generate nginx config" \
        description="Generate nginx proxy configuration" \
        help="Generate nginx configuration for reverse proxy" \
        synopsis="tdocs nginx-config <target>" \
        handler="tdocs_generate_nginx_config"

    tree_insert "help.tdocs.publish-targets" command \
        title="List publish targets" \
        description="List available publish targets" \
        help="Show configured publishing targets" \
        synopsis="tdocs publish-targets" \
        handler="tdocs_list_publish_targets"

    # Colors command
    tree_insert "help.tdocs.colors" command \
        title="Color explorer" \
        description="Interactive color explorer for TDS tokens" \
        help="Explore and test TDS color tokens interactively" \
        synopsis="tdocs colors" \
        handler="tdocs_color_explorer"
}

# Module initialization
tdocs_module_init() {
    # Create necessary directories
    mkdir -p "$TDOCS_DB_DIR" "$TDOCS_CONFIG_DIR" "$TDOCS_CACHE_DIR"

    # Initialize indexes if they don't exist
    tdoc_index_init

    # Build help tree if tree module is loaded
    if declare -p TREE_TYPE >/dev/null 2>&1; then
        _tdocs_build_help_tree
    fi
}

# Module interface functions (for Tetra module system)
tdoc_module_actions() {
    # Auto-generate from help tree if available
    if declare -F tree_to_module_actions >/dev/null 2>&1; then
        tree_to_module_actions "help.tdocs"
    else
        # Fallback to hardcoded list
        echo "init view tag ls search evidence audit discover index browse chuck about"
    fi
}

tdoc_module_properties() {
    echo "documents metadata tags indexes database"
}

tdoc_module_info() {
    echo "TDOC - Tetra Document Manager"
    echo "Purpose: Manage and categorize LLM-generated markdown documents"
    local doc_count=$(find "$TDOCS_DB_DIR" -name "*.meta" 2>/dev/null | wc -l | tr -d ' ')
    echo "Tracked Documents: $doc_count"
}

# Main tdoc command interface
tdocs() {
    local action="${1:-}"

    if [[ -z "$action" ]]; then
        _tdocs_show_help
        return 0
    fi

    shift || true

    case "$action" in
        add)
            tdocs_add_doc "$@"
            ;;
        view)
            tdocs_view_doc "$@"
            ;;
        tag)
            tdocs_tag_interactive "$@"
            ;;
        ls|list)
            tdocs_ls_docs "$@"
            ;;
        find|search)
            # find is the primary global search command (search kept for compatibility)
            tdocs_search_docs "$@"
            ;;
        evidence)
            tdocs_evidence_for_query "$@"
            ;;
        audit)
            tdocs_audit_docs "$@"
            ;;
        scan)
            tdocs_scan_docs "$@"
            ;;
        doctor)
            tdocs_doctor "$@"
            ;;
        rank)
            # Show ranking breakdown for a file
            if [[ -z "$1" ]]; then
                echo "Usage: tdocs rank <file>" >&2
                return 1
            fi
            tdoc_show_rank_breakdown "$1"
            ;;
        promote)
            # Promote document type
            if [[ -z "$1" ]]; then
                echo "Usage: tdocs promote <file>" >&2
                return 1
            fi
            tdocs_promote_doc "$1"
            ;;
        browse|repl)
            # Launch interactive REPL
            source "$TDOCS_SRC/tdocs_repl.sh"
            tdocs_repl "$@"
            ;;
        index)
            case "${1:-}" in
                --rebuild)
                    tdocs_index_rebuild
                    ;;
                *)
                    tdocs_index_status
                    ;;
            esac
            ;;
        chuck)
            tdoc_action_chuck "$@"
            ;;
        module)
            tdoc_module_docs "$@"
            ;;
        spec)
            tdoc_show_spec "$@"
            ;;
        audit-specs)
            tdoc_audit_specs "$@"
            ;;
        demo)
            # Run demo script
            if [[ -f "$TDOCS_SRC/demo_tdocs.sh" ]]; then
                "$TDOCS_SRC/demo_tdocs.sh" "$@"
            else
                echo "Demo script not found" >&2
                return 1
            fi
            ;;
        about)
            tdocs_about "$@"
            ;;
        colors)
            # Color explorer - delegate to tdocs_color_explorer
            tdocs_color_explorer "$@"
            ;;
        publish)
            # Publish docs to configured endpoint
            tdocs_publish "$@"
            ;;
        nginx-config)
            # Generate nginx proxy configuration
            tdocs_generate_nginx_config "$@"
            ;;
        publish-targets)
            # List available publish targets
            tdocs_list_publish_targets "$@"
            ;;
        help|--help|-h)
            if [[ -n "$1" ]]; then
                tdocs_help_topic "$1"
            else
                _tdocs_show_help
            fi
            ;;
        *)
            echo "Unknown command: $action" >&2
            echo "Try: tdocs help" >&2
            return 1
            ;;
    esac
}

_tdocs_show_help() {
    # Subtle color palette - intensity creates hierarchy
    local C_TITLE='\033[1;36m'      # Bright cyan (title)
    local C_CMD='\033[0;36m'        # Normal cyan (commands)
    local C_CMD_DIM='\033[2;36m'    # Dim cyan (secondary commands)
    local C_GRAY='\033[0;90m'       # Grey (descriptions)
    local C_GRAY_DIM='\033[2;37m'   # Dim grey (hints)
    local C_NC='\033[0m'

    cat <<EOF
$(echo -e "${C_TITLE}tdocs${C_NC}") - type-based doc ranking

  $(echo -e "${C_CMD}ls${C_NC}")              list (with ranks)
  $(echo -e "${C_CMD}view${C_NC}") <n>        show doc #n from ls
  $(echo -e "${C_CMD}search${C_NC}") <q>      find text
  $(echo -e "${C_CMD_DIM}rank${C_NC}") <file>     explain ranking

  $(echo -e "${C_CMD}add${C_NC}") <file>      edit metadata
  $(echo -e "${C_CMD_DIM}promote${C_NC}") <file>  notes→guide→ref
  $(echo -e "${C_CMD_DIM}scan${C_NC}")            refresh index

  $(echo -e "${C_CMD_DIM}module${C_NC}") <m>      module docs
  $(echo -e "${C_CMD_DIM}spec${C_NC}") <m>        module spec
  $(echo -e "${C_CMD_DIM}browse${C_NC}")          REPL mode

  $(echo -e "${C_CMD_DIM}publish${C_NC}") <src> <target>   publish to Spaces
  $(echo -e "${C_CMD_DIM}nginx-config${C_NC}") <target>    generate proxy config
  $(echo -e "${C_CMD_DIM}publish-targets${C_NC}")          list publish targets

$(echo -e "${C_GRAY_DIM}Types: reference 1.0 • guide 0.6 • notes 0.3${C_NC}")
$(echo -e "${C_GRAY_DIM}More:  tdocs help <topic>${C_NC}")  $(echo -e "${C_GRAY}rank filter types${C_NC}")
EOF
}

# Wrapper functions to bridge tdoc_ (singular) and tdocs_ (plural) naming
# The core functions use tdoc_ but the command interface uses tdocs_

tdocs_ls_docs() {
    # CACHE: Check for cached output (only for simple ls with no complex filters)
    local cache_file="$TDOCS_CACHE_DIR/ls_output.cache"
    local cache_signature="${*}"  # Simple signature based on args

    # Check if we should use cache (no filters that would change output)
    local use_cache=false
    if [[ -z "$cache_signature" ]] || [[ "$cache_signature" =~ ^(--numbered)?$ ]]; then
        use_cache=true
    fi

    if [[ "$use_cache" == true ]] && _tdoc_cache_is_valid "$cache_file"; then
        # Cache hit - use cached output
        cat "$cache_file"
        return 0
    fi

    # Cache miss - generate output
    if [[ "$use_cache" == true ]]; then
        # Generate and save to cache
        tdoc_list_docs "$@" | tee "$cache_file"
    else
        # Just generate without caching
        tdoc_list_docs "$@"
    fi
}

tdocs_view_doc() {
    tdoc_view_doc "$@"
}

tdocs_search_docs() {
    tdoc_search_docs "$@"
}

tdocs_tag_interactive() {
    tdoc_tag_interactive "$@"
}

tdocs_add_doc() {
    tdocs_add_doc "$@"
}

tdocs_audit_docs() {
    tdoc_audit_docs "$@"
}

tdocs_scan_docs() {
    tdoc_scan_docs "$@"
}

tdocs_doctor() {
    tdoc_doctor "$@"
}

tdocs_evidence_for_query() {
    tdoc_evidence_for_query "$@"
}

tdocs_index_rebuild() {
    tdoc_index_rebuild
}

tdocs_index_status() {
    tdoc_index_status
}

# Helper: Add left margin to piped input
_tdocs_add_margin() {
    local margin="$1"
    while IFS= read -r line; do
        printf "%*s%s\n" "$margin" "" "$line"
    done
}

tdocs_about() {
    local use_pager=true
    local left_margin=4
    local right_margin=4
    local max_width=""

    # Parse options
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --no-pager|-n)
                use_pager=false
                shift
                ;;
            --width|-w)
                max_width="$2"
                shift 2
                ;;
            --margin|-m)
                left_margin="$2"
                right_margin="$2"
                shift 2
                ;;
            --left-margin)
                left_margin="$2"
                shift 2
                ;;
            --right-margin)
                right_margin="$2"
                shift 2
                ;;
            *)
                shift
                ;;
        esac
    done

    local readme_path="$TDOCS_SRC/docs/README.md"

    if [[ ! -f "$readme_path" ]]; then
        echo "Error: Documentation not found at $readme_path" >&2
        return 1
    fi

    # Calculate content width
    local term_width=${COLUMNS:-80}
    local content_width=$((term_width - left_margin - right_margin))

    # Apply max width if specified
    if [[ -n "$max_width" ]]; then
        content_width=$max_width
    fi

    # Ensure minimum width
    [[ $content_width -lt 40 ]] && content_width=40

    # Use TDS markdown renderer if available, otherwise fall back to simpler rendering
    if declare -F tds_render_markdown >/dev/null 2>&1; then
        # TDS is available - use it with margins
        if [[ "$use_pager" == true ]]; then
            TDS_MARKDOWN_WIDTH=$content_width tds_render_markdown "$readme_path" | \
                _tdocs_add_margin "$left_margin" | \
                less -R
        else
            TDS_MARKDOWN_WIDTH=$content_width tds_render_markdown "$readme_path" | \
                _tdocs_add_margin "$left_margin"
        fi
    else
        # Fallback: Try bat, then less, then cat
        if [[ "$use_pager" == true ]]; then
            if command -v bat >/dev/null 2>&1; then
                bat --style=plain --paging=always --terminal-width=$content_width "$readme_path" | \
                    _tdocs_add_margin "$left_margin"
            elif command -v less >/dev/null 2>&1; then
                cat "$readme_path" | \
                    _tdocs_add_margin "$left_margin" | \
                    less -R
            else
                cat "$readme_path" | \
                    _tdocs_add_margin "$left_margin"
            fi
        else
            cat "$readme_path" | \
                _tdocs_add_margin "$left_margin"
        fi
    fi
}

# Export wrapper functions
export -f tdocs_ls_docs
export -f tdocs_view_doc
export -f tdocs_search_docs
export -f tdocs_tag_interactive
export -f tdocs_add_doc
export -f tdocs_audit_docs
export -f tdocs_scan_docs
export -f tdocs_evidence_for_query
export -f tdocs_index_rebuild
export -f tdocs_index_status
export -f tdocs_about
export -f _tdocs_add_margin

# Export core functions (needed for REPL and subshells)
export -f tdoc_list_docs
export -f tdoc_view_doc
export -f tdoc_search_docs
export -f tdoc_tag_interactive
export -f tdoc_init_doc
export -f tdoc_audit_docs
export -f tdoc_preview_doc
export -f tdoc_render_list_with_preview
export -f tdoc_render_compact
export -f _tdoc_truncate_path
export -f _tdoc_indent_preview
export -f _tdoc_render_bold
export -f _tdoc_style_heading
export -f _tdoc_format_preview_content
export -f tdoc_render_metadata_header
export -f tdoc_render_tag
export -f tdoc_render_tag_list
export -f tdoc_render_category_badge
export -f tdoc_render_type_badge
export -f tdoc_render_status
export -f tdoc_get_metadata
export -f tdoc_parse_frontmatter
export -f tdoc_write_frontmatter
export -f tdoc_has_frontmatter
export -f tdoc_db_create
export -f tdoc_db_get
export -f tdoc_db_get_by_path
export -f tdoc_db_update
export -f tdoc_db_list
export -f tdoc_db_delete
export -f tdoc_index_init
export -f tdoc_index_rebuild
export -f tdoc_index_status
export -f tdoc_detect_module
export -f tdoc_suggest_tags
export -f tdoc_suggest_type
export -f tdoc_suggest_category
export -f tdoc_classify_interactive
export -f tdoc_generate_timestamp
export -f tdoc_get_db_dir
export -f tdoc_get_db_path
export -f tdoc_get_tags_path
export -f tdoc_get_field
export -f _tdoc_yaml_to_json

# Export for use as command
export -f tdocs
