services:
  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    hostname: "blackbox"
    privileged: true
    volumes:
      - ./blackbox-exporter.yml:/etc/blackbox_exporter/config.yml  # Ensure this file exists on the host
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"  # Update to match the correct path

  node-exporter:
    image: prom/node-exporter:latest
    privileged: true
    command:
      - --collector.netdev
      - --collector.netstat
    ports:
      - "9100:9100"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "--nginx.scrape-uri=http://host.docker.internal/nginx_status" ]
