# Tetra Organization Secrets Configuration
# This file contains environment-specific secrets and sensitive configurations
# Should be added to .gitignore and managed securely

[organization]
name = "tetra_org"
id = "org_001"

# SSH Configuration per amigo environment
[ssh.local]
# Local development (direct access)
user_env = "mricos"
user_root = "root"
host = "localhost"
private_key_path = "~/.ssh/id_rsa"

[ssh.dev]
user_env = "tetra"
user_root = "root"
host = "dev.pixeljamarcade.com"
port = 22
private_key_path = "~/.ssh/tetra_dev_key"
jump_host = ""

[ssh.staging]
user_env = "deploy"
user_root = "root"
host = "staging.pixeljamarcade.com"
port = 22
private_key_path = "~/.ssh/tetra_staging_key"
jump_host = ""

[ssh.prod]
user_env = "deploy"
user_root = "root"
host = "prod.pixeljamarcade.com"
port = 22
private_key_path = "~/.ssh/tetra_prod_key"
jump_host = ""

# Database connections (sensitive)
[database.dev]
url = "postgres://tetra_user:dev_password@dev.pixeljamarcade.com:5432/tetra_dev"
admin_url = "postgres://postgres:admin_dev_pass@dev.pixeljamarcade.com:5432/tetra_dev"

[database.staging]
url = "postgres://tetra_user:staging_password@staging.pixeljamarcade.com:5432/tetra_staging"
admin_url = "postgres://postgres:admin_staging_pass@staging.pixeljamarcade.com:5432/tetra_staging"

[database.prod]
url = "postgres://tetra_user:prod_password@prod.pixeljamarcade.com:5432/tetra_prod"
admin_url = "postgres://postgres:admin_prod_pass@prod.pixeljamarcade.com:5432/tetra_prod"

# API Keys and tokens
[api_keys.dev]
service_token = "dev_service_token_123"
admin_token = "dev_admin_token_456"

[api_keys.staging]
service_token = "staging_service_token_789"
admin_token = "staging_admin_token_012"

[api_keys.prod]
service_token = "prod_service_token_345"
admin_token = "prod_admin_token_678"

# TLS/SSL Certificates
[certificates.dev]
cert_path = "/etc/ssl/certs/dev.pixeljamarcade.com.pem"
key_path = "/etc/ssl/private/dev.pixeljamarcade.com.key"

[certificates.staging]
cert_path = "/etc/ssl/certs/staging.pixeljamarcade.com.pem"
key_path = "/etc/ssl/private/staging.pixeljamarcade.com.key"

[certificates.prod]
cert_path = "/etc/ssl/certs/prod.pixeljamarcade.com.pem"
key_path = "/etc/ssl/private/prod.pixeljamarcade.com.key"