# Tetra Configuration File
[general]
name = "tetra"
version = "1.0.0"
environment = "development"

[database]
host = "localhost"
port = 5432
name = "tetra_db"
user = "tetra_user"

[services]
web_port = 3000
api_port = 8000
admin_port = 9000

[environments.dev]
host = "dev.tetra.local"
database_url = "postgres://localhost:5432/tetra_dev"

[environments.staging]
host = "staging.tetra.local"
database_url = "postgres://staging-db:5432/tetra_staging"

[environments.prod]
host = "prod.tetra.com"
database_url = "postgres://prod-db:5432/tetra_prod"

[deploy]
strategy = "rolling"
timeout = 300
rollback_on_failure = true