 mc \
    includes.sh \
    chroma_modular.sh \
    chroma.sh \
    main.sh \
    help.sh \
    doctor.sh \
    core/globals.sh \
    core/plugins.sh \
    core/config.sh \
    core/themes.sh \
    core/args.sh \
    core/input.sh \
    core/render.sh \
    core/parser_registry.sh \
    core/cst.sh \
    core/cst_render.sh \
    render/colors.sh \
    render/text.sh \
    render/patterns.sh \
    render/tables.sh \
    render/parser.sh \
    render/line.sh \
    parsers/markdown.sh \
    parsers/json.sh \
    parsers/toml.sh \
    parsers/latex.sh \
    parsers/claude.sh \
    plugins/line-numbers.plugin.sh \
    plugins/bat-syntax.plugin.sh \
    > chroma-core.mc
