#!/bin/bash
cwd=$(dirname $(realpath  $BASH_SOURCE))
cmd=/bin/bash
args=app.sh
daemonize \
	-E PORT=$(cat $cwd/port) \
        -c $cwd \
        -p $cwd/pid \
        -e $cwd/err \
        -o $cwd/log \
        "$cmd" "$args"
[ $? -eq 0 ] && echo "App started on PORT: $(cat $cwd/port)\n Process running as PID: $(cat $cwd/pid)" 
