#!/bin/bash
# must call this with full path name /home/user/repo/nh/stop
dir=$(dirname $BASH_SOURCE)
pid=$(cat $dir/pid)
time=$(date)
>&2 echo "BASH_SOURCE: $BASH_SOURCE"
>&2 echo "dir: $dir"
>&2 echo "$time: Killing $pid" 
kill $pid
time=$(date)
>&2 echo "$time: Killed: $pid" 
echo "" > $dir/pid 
