#!/usr/bin/env bash

# Boot Modules - Module registration and lazy loading setup

# Register all core modules for lazy loading
tetra_register_module "utils" "$TETRA_SRC/bash/utils"
tetra_register_module "tsm" "$TETRA_SRC/bash/tsm"
tetra_register_module "tkm" "$TETRA_SRC/bash/tkm"
tetra_register_module "prompt" "$TETRA_SRC/bash/prompt"
tetra_register_module "python" "$TETRA_SRC/bash/python"
tetra_register_module "nvm" "$TETRA_SRC/bash/nvm"
tetra_register_module "node" "$TETRA_SRC/bash/node"
tetra_register_module "ssh" "$TETRA_SRC/bash/ssh"
tetra_register_module "sync" "$TETRA_SRC/bash/sync"
tetra_register_module "enc" "$TETRA_SRC/bash/enc"
tetra_register_module "deploy" "$TETRA_SRC/bash/deploy"
tetra_register_module "git" "$TETRA_SRC/bash/git"
tetra_register_module "nginx" "$TETRA_SRC/bash/nginx"
tetra_register_module "pm" "$TETRA_SRC/bash/pm"
tetra_register_module "service" "$TETRA_SRC/bash/service"
tetra_register_module "sys" "$TETRA_SRC/bash/sys"
tetra_register_module "tmux" "$TETRA_SRC/bash/tmux"
tetra_register_module "user" "$TETRA_SRC/bash/user"
tetra_register_module "hotrod" "$TETRA_SRC/bash/hotrod"
tetra_register_module "ml" "$TETRA_SRC/bash/ml"
tetra_register_module "paste" "$TETRA_SRC/bash/paste"
tetra_register_module "pb" "$TETRA_SRC/bash/pb"
tetra_register_module "pbvm" "$TETRA_SRC/bash/pbvm"
tetra_register_module "pico" "$TETRA_SRC/bash/pico"
tetra_register_module "svg" "$TETRA_SRC/bash/svg"
tetra_register_module "tro" "$TETRA_SRC/bash/tro"
tetra_register_module "anthropic" "$TETRA_SRC/bash/anthropic"
tetra_register_module "reporting" "$TETRA_SRC/bash/reporting"

# Register internal modules for QA and RAG
tetra_register_module "qa" "$TETRA_SRC/bash/qa"
tetra_register_module "rag" "$TETRA_SRC/bash/rag"

# Register external modules (lazy loaded)
tetra_register_module "logtime" "$HOME/src/bash/logtime"

# Create lazy loading stubs for all module functions
tetra_create_lazy_function "rag_repl" "rag"
tetra_create_lazy_function "rag_load_tools" "rag"
tetra_create_lazy_function "tsm" "tsm"
tetra_create_lazy_function "tkm" "tkm"
tetra_create_lazy_function "tetra_python_activate" "python"
tetra_create_lazy_function "tetra_nvm_activate" "nvm"
tetra_create_lazy_function "tetra_ssh" "ssh"
tetra_create_lazy_function "tetra_sync" "sync"
tetra_create_lazy_function "tetra_deploy" "deploy"
tetra_create_lazy_function "tetra_git" "git"
tetra_create_lazy_function "tetra_nginx" "nginx"
tetra_create_lazy_function "pm" "pm"
tetra_create_lazy_function "tetra_service" "service"
tetra_create_lazy_function "tetra_tmux" "tmux"
tetra_create_lazy_function "tetra_user" "user"
tetra_create_lazy_function "hotrod" "hotrod"
tetra_create_lazy_function "tetra_ml" "ml"
tetra_create_lazy_function "pb" "pb"
tetra_create_lazy_function "pbvm" "pbvm"
tetra_create_lazy_function "pico" "pico"
tetra_create_lazy_function "tetra_svg" "svg"
tetra_create_lazy_function "tro" "tro"
tetra_create_lazy_function "anthropic" "anthropic"
tetra_create_lazy_function "qa_query" "qa"
tetra_create_lazy_function "qq" "qa"
