#!/usr/bin/env bash

# TSM Caddy Integration
# Generates per-org Caddyfiles from running TSM services
#
# Structure:
#   ~/tetra/caddy/Caddyfile              - Master config (imports org configs)
#   ~/tetra/orgs/<org>/caddy/Caddyfile   - Org-specific routes
#   ~/tetra/orgs/<org>/caddy/domain.conf - Org domain settings
#
# Usage:
#   tsm caddy init [org]      - Initialize caddy for org
#   tsm caddy sync [org]      - Sync running services to Caddyfile
#   tsm caddy sync-all        - Sync all orgs
#   tsm caddy add <svc> <port> [org] - Add single route
#   tsm caddy status [org]    - Show routes
#   tsm caddy start|stop|reload - Control caddy

CADDY_MASTER_DIR="$TETRA_DIR/caddy"
CADDY_MASTER_FILE="$CADDY_MASTER_DIR/Caddyfile"

# Get caddy dir for an org
_tsm_caddy_org_dir() {
    local org="${1:-$TSM_DEFAULT_ORG}"
    echo "$TETRA_DIR/orgs/$org/caddy"
}

# Get domain for an org
_tsm_caddy_org_domain() {
    local org="${1:-$TSM_DEFAULT_ORG}"
    local domain_conf="$(_tsm_caddy_org_dir "$org")/domain.conf"

    if [[ -f "$domain_conf" ]]; then
        source "$domain_conf"
        echo "${CADDY_DOMAIN:-localhost}"
    else
        echo "localhost"
    fi
}

# Initialize caddy structure for an org
tsm_caddy_init() {
    local org="${1:-$TSM_DEFAULT_ORG}"
    local caddy_dir="$(_tsm_caddy_org_dir "$org")"

    mkdir -p "$caddy_dir"

    # Create default domain.conf
    if [[ ! -f "$caddy_dir/domain.conf" ]]; then
        cat > "$caddy_dir/domain.conf" << 'EOF'
# Caddy domain for this org
# localhost for dev, real domain for prod
CADDY_DOMAIN="localhost"
EOF
        echo "  Created $caddy_dir/domain.conf"
    fi

    # Create empty Caddyfile
    if [[ ! -f "$caddy_dir/Caddyfile" ]]; then
        cat > "$caddy_dir/Caddyfile" << EOF
# Caddy routes for org: $org
# Auto-generated by: tsm caddy sync
EOF
        echo "  Created $caddy_dir/Caddyfile"
    fi

    # Ensure master Caddyfile exists
    mkdir -p "$CADDY_MASTER_DIR"
    if [[ ! -f "$CADDY_MASTER_FILE" ]]; then
        cat > "$CADDY_MASTER_FILE" << 'EOF'
{
    auto_https off
    admin localhost:2019
}

# Import all org configs
import ../orgs/*/caddy/Caddyfile
EOF
        echo "  Created $CADDY_MASTER_FILE"
    fi

    echo "Caddy initialized for org: $org"
}

# Sync running services to org's Caddyfile
tsm_caddy_sync() {
    local org="${1:-$TSM_DEFAULT_ORG}"
    local caddy_dir="$(_tsm_caddy_org_dir "$org")"
    local caddyfile="$caddy_dir/Caddyfile"
    local domain="$(_tsm_caddy_org_domain "$org")"

    mkdir -p "$caddy_dir"

    # Header
    cat > "$caddyfile" << EOF
# Caddy routes for org: $org
# Domain: $domain
# Auto-generated: $(date -Iseconds)
# Regenerate with: tsm caddy sync $org
EOF

    local found_services=0

    # Get running services for this org
    local service_file service_name
    for service_file in "$TETRA_DIR/orgs/$org/tsm/services-available"/*.tsm; do
        [[ -f "$service_file" ]] || continue
        service_name=$(basename "$service_file" .tsm)

        # Find running instance
        local process_dir
        for process_dir in "$TSM_PROCESSES_DIR/${service_name}-"*/; do
            [[ -d "$process_dir" ]] || continue

            local meta_file="$process_dir/meta.json"
            [[ -f "$meta_file" ]] || continue

            local port pid
            port=$(jq -r '.port // empty' "$meta_file" 2>/dev/null)
            pid=$(jq -r '.pid // empty' "$meta_file" 2>/dev/null)

            # Check if actually running
            if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
                if [[ -n "$port" && "$port" != "null" && "$port" != "none" ]]; then
                    cat >> "$caddyfile" << EOF

${service_name}.${domain} {
    reverse_proxy localhost:${port}
}
EOF
                    echo "  + ${service_name}.${domain} -> :${port}"
                    ((found_services++))
                fi
            fi
        done
    done

    if [[ $found_services -eq 0 ]]; then
        echo "  (no running services found)"
    fi

    echo "Synced org '$org' to $caddyfile"

    # Reload caddy if running
    _tsm_caddy_reload_if_running
}

# Sync ALL orgs
tsm_caddy_sync_all() {
    local org
    for org in $(_tsm_get_orgs); do
        echo "=== Syncing org: $org ==="
        tsm_caddy_sync "$org"
        echo
    done
}

# Add single route (without full sync)
tsm_caddy_add() {
    local service="$1"
    local port="$2"
    local org="${3:-$TSM_DEFAULT_ORG}"

    if [[ -z "$service" || -z "$port" ]]; then
        echo "Usage: tsm caddy add <service> <port> [org]" >&2
        return 1
    fi

    local domain="$(_tsm_caddy_org_domain "$org")"
    local caddyfile="$(_tsm_caddy_org_dir "$org")/Caddyfile"

    # Ensure caddy dir exists
    mkdir -p "$(dirname "$caddyfile")"

    # Create Caddyfile if missing
    if [[ ! -f "$caddyfile" ]]; then
        cat > "$caddyfile" << EOF
# Caddy routes for org: $org
# Domain: $domain
EOF
    fi

    # Check if route already exists
    if grep -q "^${service}\.${domain}" "$caddyfile" 2>/dev/null; then
        echo "Route ${service}.${domain} already exists, updating..."
        # Remove old entry (multiline block)
        sed -i.bak "/^${service}\.${domain}/,/^}/d" "$caddyfile"
        rm -f "${caddyfile}.bak"
    fi

    # Append route
    cat >> "$caddyfile" << EOF

${service}.${domain} {
    reverse_proxy localhost:${port}
}
EOF

    echo "Added ${service}.${domain} -> :${port}"

    _tsm_caddy_reload_if_running
}

# Remove route
tsm_caddy_rm() {
    local service="$1"
    local org="${2:-$TSM_DEFAULT_ORG}"

    if [[ -z "$service" ]]; then
        echo "Usage: tsm caddy rm <service> [org]" >&2
        return 1
    fi

    local domain="$(_tsm_caddy_org_domain "$org")"
    local caddyfile="$(_tsm_caddy_org_dir "$org")/Caddyfile"

    if [[ ! -f "$caddyfile" ]]; then
        echo "No Caddyfile for org: $org" >&2
        return 1
    fi

    # Remove entry (multiline block)
    if grep -q "^${service}\.${domain}" "$caddyfile" 2>/dev/null; then
        sed -i.bak "/^${service}\.${domain}/,/^}/d" "$caddyfile"
        rm -f "${caddyfile}.bak"
        echo "Removed ${service}.${domain}"
        _tsm_caddy_reload_if_running
    else
        echo "Route not found: ${service}.${domain}"
        return 1
    fi
}

# Show current routes
tsm_caddy_status() {
    local org="${1:-}"

    echo "Caddy Status"
    echo "============"

    # Check if caddy is running
    if pgrep -x caddy >/dev/null 2>&1; then
        echo "Caddy: running (PID $(pgrep -x caddy))"
    else
        echo "Caddy: not running"
    fi
    echo

    if [[ -n "$org" ]]; then
        local caddyfile="$(_tsm_caddy_org_dir "$org")/Caddyfile"
        local domain="$(_tsm_caddy_org_domain "$org")"
        echo "=== $org (domain: $domain) ==="
        if [[ -f "$caddyfile" ]]; then
            # Extract routes
            grep -E '^\S+\.' "$caddyfile" | sed 's/ {$//' | while read -r route; do
                local port=$(grep -A1 "^${route}" "$caddyfile" | grep reverse_proxy | grep -oE '[0-9]+$')
                printf "  %-30s -> :%s\n" "$route" "$port"
            done
        else
            echo "  (no Caddyfile)"
        fi
    else
        # Show all orgs
        for org in $(_tsm_get_orgs); do
            local caddyfile="$(_tsm_caddy_org_dir "$org")/Caddyfile"
            local domain="$(_tsm_caddy_org_domain "$org")"
            if [[ -f "$caddyfile" ]]; then
                echo "=== $org (domain: $domain) ==="
                grep -E '^\S+\.' "$caddyfile" | sed 's/ {$//' | while read -r route; do
                    local port=$(grep -A1 "^${route}" "$caddyfile" | grep reverse_proxy | grep -oE '[0-9]+$')
                    printf "  %-30s -> :%s\n" "$route" "$port"
                done
                echo
            fi
        done
    fi
}

# Reload caddy if running
_tsm_caddy_reload_if_running() {
    if pgrep -x caddy >/dev/null 2>&1; then
        if caddy reload --config "$CADDY_MASTER_FILE" 2>/dev/null; then
            echo "Caddy reloaded"
        else
            echo "Caddy reload failed" >&2
        fi
    fi
}

# Start caddy
tsm_caddy_start() {
    if pgrep -x caddy >/dev/null 2>&1; then
        echo "Caddy already running (PID $(pgrep -x caddy))"
        return 0
    fi

    if [[ ! -f "$CADDY_MASTER_FILE" ]]; then
        echo "Master Caddyfile not found. Run: tsm caddy init" >&2
        return 1
    fi

    caddy start --config "$CADDY_MASTER_FILE"
    echo "Caddy started"
}

# Stop caddy
tsm_caddy_stop() {
    if ! pgrep -x caddy >/dev/null 2>&1; then
        echo "Caddy not running"
        return 0
    fi

    caddy stop
    echo "Caddy stopped"
}

# CLI dispatcher
tsm_caddy() {
    local cmd="${1:-status}"
    shift || true

    case "$cmd" in
        init)
            tsm_caddy_init "$@"
            ;;
        sync)
            tsm_caddy_sync "$@"
            ;;
        syncall|sync-all)
            tsm_caddy_sync_all
            ;;
        add)
            tsm_caddy_add "$@"
            ;;
        rm|remove)
            tsm_caddy_rm "$@"
            ;;
        status|ls)
            tsm_caddy_status "$@"
            ;;
        start)
            tsm_caddy_start
            ;;
        stop)
            tsm_caddy_stop
            ;;
        reload)
            if [[ -f "$CADDY_MASTER_FILE" ]]; then
                caddy reload --config "$CADDY_MASTER_FILE"
            else
                echo "Master Caddyfile not found" >&2
                return 1
            fi
            ;;
        edit)
            local org="${1:-$TSM_DEFAULT_ORG}"
            local caddyfile="$(_tsm_caddy_org_dir "$org")/Caddyfile"
            ${EDITOR:-vim} "$caddyfile"
            ;;
        *)
            cat << 'EOF'
Usage: tsm caddy <command> [args]

Commands:
  init [org]              Initialize caddy for org
  sync [org]              Sync running services to Caddyfile
  sync-all                Sync all orgs
  add <svc> <port> [org]  Add single route
  rm <svc> [org]          Remove route
  status [org]            Show routes
  edit [org]              Edit org's Caddyfile
  start                   Start caddy
  stop                    Stop caddy
  reload                  Reload caddy config

Examples:
  tsm caddy init tetra
  tsm caddy sync tetra
  tsm caddy add myapp 8080
  tsm caddy status
EOF
            return 1
            ;;
    esac
}

export -f tsm_caddy tsm_caddy_init tsm_caddy_sync tsm_caddy_sync_all
export -f tsm_caddy_add tsm_caddy_rm tsm_caddy_status
export -f tsm_caddy_start tsm_caddy_stop
export -f _tsm_caddy_org_dir _tsm_caddy_org_domain _tsm_caddy_reload_if_running
