global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['10.124.0.4:9100']
        labels:
          env: 'dev'
          host: 'pxjam-arcade-dev01' 
