.\" Manpage for Nodeholder.
.\" Contact mike@lenan.net to correct errors or typos.
.TH man 8 "01 Sep 2020" "v001m1" "Nodeholder man page"
.SH NAME
\fBNodeholder\fP is a  set of command line functions for securely configuring, running and mointoring virtual private networks and hosts.

.SH SYNOPSIS
\fBnodeholder-\fP[OPTIONS]

.SH OPTIONS

.TP
\fBconfigure\fP $ip config.sh
copies config.sh and runs it. Disables root, creates admin account
with original root/.ssh/authorized_key. For now config.sh file must 
be in the local directory where this is called.

.TP
\fBgenerate-aliases\fP
Creates shell aliases to 'functions at a distance'. for example,
alias child-admin-init='ssh admin@child_ip 'admin-init'

.TP
\fBinstall-admin\fP
copies admin.sh to admin account and and runs it. The virtual private server is now a nodeholder child that may host \fBnodes\fP.

.TP
\fBrefresh-admin\fP
copies admin.sh to admin account, does not run it. Used for admin@nodeholder acommands. The virtual private server is now a nodeholder child that may host \fBnodes\fP.

.TP
\fBinstall-admin\fB $ip
 copies admin.sh 
and adds code to source admin.sh in admin@$ip:admin.sh
which enables configuration at a distance via \fBnodeholder-\fP
commands.

.TP
\fBcreate-node\fP nodename
Creates a node (Unix user) which hosts multiple apps.

.SS ADMIN@$IP OPTIONS 
After child nodeholder at $ip is setup, you may use the admin interface
via admin@$ip 'admin-option'

.TP
\fBadmin-create-app\fP $nodeName $repoURL $appName
If repo is private, make sure you have added local public 
SSH key to node@$ip:.ssh/authorized_keys. Upon completion,
the repo will be copied in a directory called appName 
containing appName/nh directory. This nh directory 
contains files copied from admin@$mother/buildpak.


.TP
\fBadmin-create-port\fP
Generates a port number, marks it as used, adds to admin@$ip:ports/

.TP
\fBadmin-delete-port\fP
Frees a system port.

.TP
\fBadmin-delete-app\fP
Frees port and deletes repo.


.SH THEORY OF OPERATION
nodeholder-config usese
scp to copy and execute the config.sh file on
root@child. After this one-time process is complete, the
root account is disbled and only the admin user can
authenticate with SSHd on the child.


nodeholder-install-admin $ip copies admin.sh 
and adds code to source admin.sh in admin@$ip:admin.sh
which enables configuration at a distance via \fBnodeholder-\fP*
commands.

nodeholder-create-node creates a node (implemented 
as unix user with no password) 
that can hold multiple apps with one port per app. Typically 
multiple users would provide public SSH keys that are 
added to node@$ip:./ssh/authorized_keys. This allows
teams to share a node for multiple network apps.

admin-create-app creates network-aware applications
under nodes which are controlled remotely via 
node@$ip:node/app/nh/{start,stop,status}

.SH SEE ALSO
dotool(8)
.SH BUGS
No known bugs (Ha!).
.SH AUTHOR
Mike Ricos (mike@lenan.net), Zach Overhulser (zoverlvx@gmail.com)
