# Web Application Organization Template
# Organization: ${ORG_NAME}

[metadata]
name = "${ORG_NAME}"
type = "webapp"
description = "Standard web application with frontend and backend services"
created_from_template = "webapp"

[services.frontend]
type = "nodejs"
port = 3000
path = "frontend"
start_command = "npm run dev"
dependencies = ["backend"]

[services.backend]
type = "nodejs"
port = 8000
path = "backend"
start_command = "npm run dev"
env_file = "backend/.env"

[services.database]
type = "postgres"
port = 5432
data_path = "data/postgres"

[environments.development]
frontend_port = 3000
backend_port = 8000
database_url = "postgresql://localhost:5432/${ORG_NAME}_dev"

[environments.staging]
frontend_port = 3001
backend_port = 8001
database_url = "postgresql://localhost:5432/${ORG_NAME}_staging"

[environments.production]
frontend_port = 80
backend_port = 8080
database_url = "postgresql://localhost:5432/${ORG_NAME}_prod"