#!/usr/bin/env bash
# nginx_docs.sh - Org module integration for nginx docs proxy
# Provides org action interface to docs_proxy.sh

# Load nginx docs proxy module
NGINX_DOCS_MODULE="$TETRA_SRC/bash/nginx/docs_proxy.sh"
if [[ -f "$NGINX_DOCS_MODULE" ]]; then
    source "$NGINX_DOCS_MODULE"
else
    echo "Error: nginx docs_proxy module not found: $NGINX_DOCS_MODULE" >&2
    return 1
fi

# Org action: nginx.docs.generate <doc-type>
org_nginx_docs_generate() {
    nginx_docs_generate_config "$@"
}

# Org action: nginx.docs.deploy <doc-type> [env]
org_nginx_docs_deploy() {
    nginx_docs_deploy_config "$@"
}

# Org action: nginx.docs.list
org_nginx_docs_list() {
    nginx_docs_list
}

# Org action: nginx.docs.show <doc-type>
org_nginx_docs_show() {
    local doc_type="$1"
    local org_name="${TETRA_ORG:?TETRA_ORG must be set}"

    if [[ -z "$doc_type" ]]; then
        echo "Error: doc-type required" >&2
        echo "Usage: org nginx.docs.show <doc-type>" >&2
        return 1
    fi

    local toml_file="$TETRA_DIR/orgs/$org_name/tetra.toml"
    local section_name="publishing.$doc_type"

    echo "═══════════════════════════════════════════════════════════"
    echo "  DOC CONFIG: $doc_type"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Section: [$section_name]"
    echo ""

    awk "/^\[$section_name\]/ {found=1; next} found && /^\[/ {exit} found {print}" "$toml_file"
    echo ""

    # Check for generated files
    local nginx_dir="$TETRA_DIR/orgs/$org_name/nginx"
    local subdomain
    subdomain=$(awk "/^\[$section_name\]/ {found=1; next} found && /^\[/ {exit} found && /^subdomain/ {print}" "$toml_file" | cut -d'=' -f2 | tr -d ' "')

    if [[ -n "$subdomain" ]]; then
        echo "Generated Files:"
        if [[ -f "$nginx_dir/${subdomain}.conf" ]]; then
            echo "  ✓ Nginx config: $nginx_dir/${subdomain}.conf"
        else
            echo "  ✗ Nginx config: not generated"
        fi

        if [[ -f "$nginx_dir/${subdomain}.htpasswd" ]]; then
            echo "  ✓ htpasswd: $nginx_dir/${subdomain}.htpasswd"
        else
            echo "  ✗ htpasswd: not found (public docs)"
        fi
        echo ""
    fi
}

# Org action: nginx.docs.init <doc-type> <subdomain>
# Interactive setup for a new doc subdomain
org_nginx_docs_init() {
    local doc_type="$1"
    local subdomain="$2"
    local org_name="${TETRA_ORG:?TETRA_ORG must be set}"

    if [[ -z "$doc_type" ]] || [[ -z "$subdomain" ]]; then
        echo "Error: doc-type and subdomain required" >&2
        echo "Usage: org nginx.docs.init <doc-type> <subdomain>" >&2
        echo "Example: org nginx.docs.init api-docs api-docs.pixeljamarcade.com" >&2
        return 1
    fi

    echo "═══════════════════════════════════════════════════════════"
    echo "  INITIALIZE DOC SUBDOMAIN"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Doc Type:  $doc_type"
    echo "Subdomain: $subdomain"
    echo ""

    # Interactive prompts
    read -p "Spaces bucket [pja-docs-private]: " bucket
    bucket="${bucket:-pja-docs-private}"

    read -p "Bucket prefix [${doc_type}/]: " prefix
    prefix="${prefix:-${doc_type}/}"

    read -p "Auth required? [y/N]: " auth_required
    auth_required="${auth_required:-n}"

    local auth_realm=""
    local auth_users_var=""
    if [[ "$auth_required" =~ ^[Yy]$ ]]; then
        read -p "Auth realm [Documentation]: " auth_realm
        auth_realm="${auth_realm:-Documentation}"

        local default_var="${doc_type^^}_USERS"
        default_var="${default_var//[-.]/_}"
        read -p "Auth users env var [$default_var]: " auth_users_var
        auth_users_var="${auth_users_var:-$default_var}"

        echo ""
        echo "⚠️  Don't forget to add to secrets.env:"
        echo "   $auth_users_var=username:\$apr1\$...(htpasswd hash)"
        echo ""
        echo "Generate with: htpasswd -nb username password"
        echo ""
    fi

    # Build TOML section
    local toml_file="$TETRA_DIR/orgs/$org_name/tetra.toml"
    local section_name="publishing.$doc_type"

    echo "Adding to $toml_file:"
    echo ""
    cat << EOF
[$section_name]
symbol = "@$doc_type"
type = "spaces"
bucket = "$bucket"
prefix = "$prefix"
subdomain = "$subdomain"
EOF

    if [[ -n "$auth_realm" ]]; then
        cat << EOF
auth_required = true
auth_realm = "$auth_realm"
auth_users_var = "$auth_users_var"
EOF
    fi

    echo ""
    read -p "Add this to tetra.toml? [y/N]: " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        {
            echo ""
            echo "# ═══════════════════════════════════════════════════════════"
            echo "# DOC PUBLISHING - $doc_type"
            echo "# Generated by org nginx.docs.init on $(date)"
            echo "# ═══════════════════════════════════════════════════════════"
            echo ""
            echo "[$section_name]"
            echo "symbol = \"@$doc_type\""
            echo "type = \"spaces\""
            echo "bucket = \"$bucket\""
            echo "prefix = \"$prefix\""
            echo "subdomain = \"$subdomain\""
            if [[ -n "$auth_realm" ]]; then
                echo "auth_required = true"
                echo "auth_realm = \"$auth_realm\""
                echo "auth_users_var = \"$auth_users_var\""
            fi
        } >> "$toml_file"

        echo "✓ Added to tetra.toml"
        echo ""
        echo "Next steps:"
        echo "1. Generate nginx config: org nginx.docs.generate $doc_type"
        if [[ -n "$auth_users_var" ]]; then
            echo "2. Add credentials to secrets.env"
        fi
        echo "3. Deploy: org nginx.docs.deploy $doc_type prod"
    else
        echo "Cancelled"
    fi
}

# Export functions
export -f org_nginx_docs_generate
export -f org_nginx_docs_deploy
export -f org_nginx_docs_list
export -f org_nginx_docs_show
export -f org_nginx_docs_init
