#!/usr/bin/env bash
# org_storage.sh - S3/Spaces bucket provisioning and management
#
# Commands:
#   org storage init     Create S3 bucket, configure tetra.toml
#   org storage status   Show bucket and connectivity status
#   org storage test     Upload/download test object
#
# Configuration:
#   Reads [storage.s3] from org's tetra.toml
#   Falls back to environment variables:
#     DO_SPACES_KEY, DO_SPACES_SECRET
#     TSM_LOG_S3_BUCKET, TSM_LOG_S3_ENDPOINT

# === HELPERS ===

# Get storage config from tetra.toml
_org_storage_get_config() {
    local toml
    toml=$(org_toml_path 2>/dev/null) || return 1

    local bucket endpoint region prefix
    bucket=$(grep -E '^bucket\s*=' "$toml" 2>/dev/null | head -1 | sed 's/.*=\s*"\{0,1\}\([^"]*\)"\{0,1\}/\1/')
    endpoint=$(grep -E '^endpoint\s*=' "$toml" 2>/dev/null | head -1 | sed 's/.*=\s*"\{0,1\}\([^"]*\)"\{0,1\}/\1/')
    region=$(grep -E '^region\s*=' "$toml" 2>/dev/null | head -1 | sed 's/.*=\s*"\{0,1\}\([^"]*\)"\{0,1\}/\1/')
    prefix=$(grep -E '^prefix\s*=' "$toml" 2>/dev/null | head -1 | sed 's/.*=\s*"\{0,1\}\([^"]*\)"\{0,1\}/\1/')

    # Export for use by caller
    STORAGE_BUCKET="${bucket:-$TSM_LOG_S3_BUCKET}"
    STORAGE_ENDPOINT="${endpoint:-$TSM_LOG_S3_ENDPOINT:-https://nyc3.digitaloceanspaces.com}"
    STORAGE_REGION="${region:-nyc3}"
    STORAGE_PREFIX="${prefix:-tsm/logs/}"
}

# Check credentials
_org_storage_check_creds() {
    if [[ -z "$DO_SPACES_KEY" || -z "$DO_SPACES_SECRET" ]]; then
        echo "Missing credentials: DO_SPACES_KEY and DO_SPACES_SECRET required" >&2
        echo "" >&2
        echo "Set via environment or in org's secrets.env:" >&2
        echo "  export DO_SPACES_KEY=your-key" >&2
        echo "  export DO_SPACES_SECRET=your-secret" >&2
        return 1
    fi
    return 0
}

# Setup AWS CLI environment for DO Spaces
_org_storage_setup_aws() {
    export AWS_ACCESS_KEY_ID="$DO_SPACES_KEY"
    export AWS_SECRET_ACCESS_KEY="$DO_SPACES_SECRET"
    export AWS_DEFAULT_REGION="${STORAGE_REGION:-nyc3}"
}

# === INIT ===

# Initialize storage - create bucket, write config
org_storage_init() {
    local name="${1:-$(org_active 2>/dev/null)}"
    [[ "$name" == "$ORG_NO_ACTIVE" ]] && name=""

    if [[ -z "$name" ]]; then
        echo "Usage: org storage init [org_name]" >&2
        return 1
    fi

    local org_dir="$TETRA_DIR/orgs/$name"
    [[ ! -d "$org_dir" ]] && { echo "Org not found: $name" >&2; return 1; }

    echo "Storage Init: $name"
    echo ""

    # Check for AWS CLI
    if ! command -v aws &>/dev/null; then
        echo "AWS CLI not found. Install with: brew install awscli" >&2
        return 1
    fi

    # Check credentials
    if ! _org_storage_check_creds; then
        return 1
    fi

    # Load existing config or prompt
    _org_storage_get_config

    local bucket="${STORAGE_BUCKET:-}"
    local endpoint="${STORAGE_ENDPOINT:-https://nyc3.digitaloceanspaces.com}"
    local region="${STORAGE_REGION:-nyc3}"

    # Interactive prompts if not configured
    if [[ -z "$bucket" ]]; then
        echo "S3/Spaces Configuration"
        echo "-----------------------"
        echo ""
        echo -n "Bucket name (e.g., ${name}-logs): "
        read -r bucket
        [[ -z "$bucket" ]] && bucket="${name}-logs"
    fi

    if [[ "$endpoint" == "https://nyc3.digitaloceanspaces.com" ]]; then
        echo ""
        echo "Endpoint options:"
        echo "  1) nyc3.digitaloceanspaces.com (default)"
        echo "  2) sfo3.digitaloceanspaces.com"
        echo "  3) Custom endpoint"
        echo -n "Select [1-3, default=1]: "
        read -r choice
        case "$choice" in
            2) endpoint="https://sfo3.digitaloceanspaces.com"; region="sfo3" ;;
            3)
                echo -n "Enter endpoint URL: "
                read -r endpoint
                echo -n "Enter region: "
                read -r region
                ;;
            *) endpoint="https://nyc3.digitaloceanspaces.com"; region="nyc3" ;;
        esac
    fi

    echo ""
    echo "Creating bucket: $bucket"
    echo "  Endpoint: $endpoint"
    echo "  Region:   $region"
    echo ""

    # Setup AWS credentials
    _org_storage_setup_aws
    export AWS_ENDPOINT_URL="$endpoint"

    # Create bucket
    if aws s3 mb "s3://$bucket" --endpoint-url "$endpoint" 2>/dev/null; then
        echo "Bucket created: $bucket"
    else
        # Check if bucket already exists
        if aws s3 ls "s3://$bucket" --endpoint-url "$endpoint" &>/dev/null; then
            echo "Bucket already exists: $bucket"
        else
            echo "Failed to create bucket: $bucket" >&2
            return 1
        fi
    fi

    # Write config to tetra.toml sections
    local sections_dir="$org_dir/sections"
    if [[ -d "$sections_dir" ]]; then
        local storage_file="$sections_dir/30-storage.toml"
        cat > "$storage_file" << EOF
# Storage configuration
# Auto-generated by: org storage init

[storage.s3]
bucket = "$bucket"
endpoint = "$endpoint"
region = "$region"
prefix = "tsm/logs/"
EOF
        echo ""
        echo "Created: sections/30-storage.toml"
        echo ""
        echo "Run 'org build' to update tetra.toml"
    else
        # Append to tetra.toml directly
        local toml="$org_dir/tetra.toml"
        if [[ -f "$toml" ]]; then
            echo "" >> "$toml"
            echo "[storage.s3]" >> "$toml"
            echo "bucket = \"$bucket\"" >> "$toml"
            echo "endpoint = \"$endpoint\"" >> "$toml"
            echo "region = \"$region\"" >> "$toml"
            echo "prefix = \"tsm/logs/\"" >> "$toml"
            echo ""
            echo "Updated: tetra.toml"
        fi
    fi

    # Set environment variables for TSM
    echo ""
    echo "Set these in your environment or secrets.env:"
    echo "  export TSM_LOG_S3_BUCKET=\"$bucket\""
    echo "  export TSM_LOG_S3_ENDPOINT=\"$endpoint\""
    echo ""
    echo "Test with: org storage test"
}

# === STATUS ===

org_storage_status() {
    local name="${1:-$(org_active 2>/dev/null)}"
    [[ "$name" == "$ORG_NO_ACTIVE" ]] && name=""

    if [[ -z "$name" ]]; then
        echo "Usage: org storage status [org_name]" >&2
        return 1
    fi

    echo "Storage Status: $name"
    echo ""

    # Load config
    _org_storage_get_config

    if [[ -z "$STORAGE_BUCKET" ]]; then
        echo "Not configured"
        echo ""
        echo "Run: org storage init"
        return 0
    fi

    echo "Bucket:   $STORAGE_BUCKET"
    echo "Endpoint: $STORAGE_ENDPOINT"
    echo "Region:   $STORAGE_REGION"
    echo "Prefix:   $STORAGE_PREFIX"
    echo ""

    # Check credentials
    if ! _org_storage_check_creds 2>/dev/null; then
        echo "Credentials: MISSING"
        return 1
    fi
    echo "Credentials: OK"

    # Test connectivity
    _org_storage_setup_aws
    export AWS_ENDPOINT_URL="$STORAGE_ENDPOINT"

    if aws s3 ls "s3://$STORAGE_BUCKET" --endpoint-url "$STORAGE_ENDPOINT" &>/dev/null; then
        echo "Connection: OK"

        # Count objects
        local count
        count=$(aws s3 ls "s3://$STORAGE_BUCKET/$STORAGE_PREFIX" --endpoint-url "$STORAGE_ENDPOINT" 2>/dev/null | wc -l | tr -d ' ')
        echo "Objects:    $count files in $STORAGE_PREFIX"
    else
        echo "Connection: FAILED"
        return 1
    fi
}

# === TEST ===

org_storage_test() {
    local name="${1:-$(org_active 2>/dev/null)}"
    [[ "$name" == "$ORG_NO_ACTIVE" ]] && name=""

    if [[ -z "$name" ]]; then
        echo "Usage: org storage test [org_name]" >&2
        return 1
    fi

    echo "Storage Test: $name"
    echo ""

    # Load config
    _org_storage_get_config

    if [[ -z "$STORAGE_BUCKET" ]]; then
        echo "Not configured. Run: org storage init" >&2
        return 1
    fi

    # Check credentials
    if ! _org_storage_check_creds; then
        return 1
    fi

    _org_storage_setup_aws
    export AWS_ENDPOINT_URL="$STORAGE_ENDPOINT"

    local test_file="/tmp/org-storage-test-$$"
    local test_key="${STORAGE_PREFIX}test/connectivity-$(date +%s).txt"

    # Create test file
    echo "Storage connectivity test from $(hostname) at $(date -Iseconds)" > "$test_file"

    echo "1. Uploading test file..."
    if aws s3 cp "$test_file" "s3://$STORAGE_BUCKET/$test_key" --endpoint-url "$STORAGE_ENDPOINT"; then
        echo "   OK"
    else
        echo "   FAILED" >&2
        rm -f "$test_file"
        return 1
    fi

    echo "2. Downloading test file..."
    local download_file="/tmp/org-storage-test-dl-$$"
    if aws s3 cp "s3://$STORAGE_BUCKET/$test_key" "$download_file" --endpoint-url "$STORAGE_ENDPOINT"; then
        echo "   OK"
    else
        echo "   FAILED" >&2
        rm -f "$test_file"
        return 1
    fi

    echo "3. Verifying content..."
    if diff -q "$test_file" "$download_file" &>/dev/null; then
        echo "   OK"
    else
        echo "   MISMATCH" >&2
        rm -f "$test_file" "$download_file"
        return 1
    fi

    echo "4. Cleaning up test file..."
    if aws s3 rm "s3://$STORAGE_BUCKET/$test_key" --endpoint-url "$STORAGE_ENDPOINT"; then
        echo "   OK"
    else
        echo "   FAILED (non-critical)" >&2
    fi

    rm -f "$test_file" "$download_file"

    echo ""
    echo "All tests passed!"
}

# === SUBCOMMAND ROUTER ===

org_storage() {
    local subcmd="${1:-status}"
    shift 2>/dev/null || true

    case "$subcmd" in
        init)
            org_storage_init "$@"
            ;;
        status|"")
            org_storage_status "$@"
            ;;
        test)
            org_storage_test "$@"
            ;;
        help|--help|-h)
            echo "org storage - S3/Spaces bucket management"
            echo ""
            echo "Commands:"
            echo "  init [org]    Create bucket, configure tetra.toml"
            echo "  status [org]  Show bucket and connectivity status"
            echo "  test [org]    Upload/download test object"
            echo ""
            echo "Requirements:"
            echo "  - AWS CLI (brew install awscli)"
            echo "  - DO_SPACES_KEY and DO_SPACES_SECRET in environment"
            ;;
        *)
            echo "Unknown storage command: $subcmd" >&2
            echo "Try: org storage help" >&2
            return 1
            ;;
    esac
}

# === EXPORTS ===

export -f org_storage org_storage_init org_storage_status org_storage_test
export -f _org_storage_get_config _org_storage_check_creds _org_storage_setup_aws
