/**
 * TDS Color Sync for Dashboard
 *
 * Ensures web dashboard colors match CLI TDS theme.
 *
 * Usage options:
 *   1. Static CSS: Import tds-vars.css (generated by: tds css --sync)
 *   2. Runtime sync: Call TdsColors.sync() on page load
 *   3. Hybrid: Use static CSS with periodic runtime refresh
 *
 * CSS Variables synced:
 *   --paper-dark, --paper-mid, --paper-light
 *   --ink, --ink-muted
 *   --border
 *   --one (error), --two (success), --three (warning), --four (accent)
 */

const TdsColors = {
    // Fallback colors (match shared.css defaults)
    defaults: {
        paperDark: '#0a0a0a',
        paperMid: '#1a1a1a',
        paperLight: '#2a2a2a',
        ink: '#e0e0e0',
        inkMuted: '#666666',
        border: '#333333',
        one: '#ff6b6b',
        two: '#4ecdc4',
        three: '#ffe66d',
        four: '#6b5ce7'
    },

    // Map JSON keys to CSS variable names
    cssVarMap: {
        paperDark: '--paper-dark',
        paperMid: '--paper-mid',
        paperLight: '--paper-light',
        ink: '--ink',
        inkMuted: '--ink-muted',
        border: '--border',
        one: '--one',
        two: '--two',
        three: '--three',
        four: '--four'
    },

    // Current colors (populated after sync)
    current: null,

    /**
     * Fetch colors from TDS API and apply to document
     * @returns {Promise<object>} The color palette
     */
    async sync() {
        try {
            const res = await fetch('/api/tds/colors');
            const data = await res.json();

            if (data.colors) {
                this.apply(data.colors);
                this.current = data.colors;
                console.log('[TDS] Colors synced from', data.source);
                return data.colors;
            }
        } catch (err) {
            console.warn('[TDS] Color sync failed, using defaults:', err.message);
            this.apply(this.defaults);
            this.current = this.defaults;
        }
        return this.defaults;
    },

    /**
     * Apply colors to document root
     * @param {object} colors - Color object with camelCase keys
     */
    apply(colors) {
        const root = document.documentElement;

        for (const [key, cssVar] of Object.entries(this.cssVarMap)) {
            const value = colors[key];
            if (value) {
                root.style.setProperty(cssVar, value);
            }
        }
    },

    /**
     * Get current value of a CSS variable
     * @param {string} varName - CSS variable name (e.g., '--one')
     * @returns {string} The color value
     */
    get(varName) {
        return getComputedStyle(document.documentElement).getPropertyValue(varName).trim();
    },

    /**
     * Get all current CSS color variables
     * @returns {object} Map of CSS var names to values
     */
    getAll() {
        const result = {};
        for (const cssVar of Object.values(this.cssVarMap)) {
            result[cssVar] = this.get(cssVar);
        }
        return result;
    },

    /**
     * Auto-sync on page load (call from script)
     */
    init() {
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => this.sync());
        } else {
            this.sync();
        }
    }
};

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = TdsColors;
}
