alias tpl=tetra_pm_list
alias tps=tetra_pm_start
#alias tpa=tetra_pm_attach # used for tetra_python_activate
alias tpk=tetra_pm_stop
alias tpr=tetra_pm_restart
alias tpka=tetra_pm_kill_all
alias tplt="tail $TETRA_LOG"
alias tpks=tetra_pm_kill_sessions
alias tpmi=tetra_pm_main_init
